### ISSUE TITLE
Typo in Fdroid page

### ISSUE THREAD

**Issue by array-in-a-matrix** [krille-chan/fluffychat#1007]
The description for fluffychat mentions clients compatible with it refrencing nheko as nekho.

https://f-droid.org/packages/chat.fluffy.fluffychat/
https://github.com/Nheko-Reborn/nheko

![IMG_20240410_042704](https://github.com/krille-chan/fluffychat/assets/78233840/fdba75f0-8a7b-4722-93af-db9e80622920)

**Comment by krille-chan** [comment]
Thank you so much :) have fixed it

**Comment by array-in-a-matrix** [comment]
I just checked it, it doesn't seem fixed?
