### ISSUE TITLE
"Push notifications not available" on Android even if they should be

### ISSUE THREAD

**Issue by Powersource** [krille-chan/fluffychat#1014]
### Bug Description

The app is telling me I have Google services disabled and I need to setup ntfy. But this is a default samsung phone and i haven't been messing around with Google services. I have enabled notification permissions for the app.

![Screenshot_20240410_234815](https://github.com/krille-chan/fluffychat/assets/1427063/f55ab417-186b-4097-a154-9f683b58be0f)

### Steps to Reproduce

I just open the app and I get the above modal

### Expected Behavior

Notifications to work without configuration 

### App Version

1.18.0

### Additional Platform Information

samsung s20 5g, android 13

**Comment by Mikaela** [comment]
You probably installed F-Droid build which doesn't contain Google support due to it being propietary, so you should follow https://github.com/krille-chan/fluffychat/wiki/Push-Notifications-without-Google-Services

**Comment by LinqLover** [comment]
> You probably installed F-Droid build which doesn't contain Google support due to it being propietary, so you should follow https://github.com/krille-chan/fluffychat/wiki/Push-Notifications-without-Google-Services

Met this great app yesterday and just run into the same issue! For feedback, it might be helpful mention in the [FAQ](https://fluffychat.im/faq/#how_can_i_get_push_notifications_without_google_services) that the F-Droid builds do not contain Google Play Services support.

Are there any plans to change this? I don't want to rely more than necessary on Google Play Store but setting up a second notification service sounds battery-draining 🤔
