### ISSUE TITLE
Flatpak: Flathub Verified Badge

### ISSUE THREAD

**Issue by cassiofb-dev** [krille-chan/fluffychat#1016]
### Feature Description

Recently flathub made some changes in the UI and the unverified badge seems like a warning alert.
I saw that most active contributor on flatpak manifest is also the original project developer, so it should meet all the requirements for a verified badge.

> Verification is a process by which Flathub can confirm that an app is published by its original developer or a third party approved by the developer. This is done by verifying the developer's identity using a link to their website or to their account on a source code hosting site. The methods available for verification depend on the app ID.
- From: https://docs.flathub.org/docs/for-app-authors/verification

### Rationale

It seems like something really important but users could be worried seeing this new badge layout like a warning alert.

### Additional Context

![image](https://github.com/krille-chan/fluffychat/assets/61878987/97e73412-0f32-422f-8b7a-1794a281efe7)

**Comment by krille-chan** [comment]
Done :) https://flathub.org/de/apps/im.fluffychat.Fluffychat
