### ISSUE TITLE
Feature Request: Theme support for Android 12/Google's Material You theming

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#107]
Forgive me, this is mostly a copy/paste from my feature Request for element-android.  

#### Description
In Android 12, Google has added support for Material You, which automatically picks colors for apps/settings/notifications based on your home wallpaper.

https://www.xda-developers.com/material-you/

#### Describe the solution you'd like.
For FluffyChat to support Material You on Android 12.

#### Describe alternatives you've considered.
No alternatives.

#### Additional context
Google has not yet published third-party docs on how to accomplish this, but several apps have already reverse-engineered support on their own.

https://www.xda-developers.com/the-first-apps-using-material-you-theming-are-here/amp/

There is also a library that can be packaged into an app.

https://www.xda-developers.com/android-12-material-you-dynamic-theming-library/

https://github.com/KieronQuinn/MonetCompat

It also sounds like Flutter's SDK will be ready for this in short order.

https://9to5google.com/2021/05/20/flutter-sdk-material-you/

/issue fluffy

**Comment by Henry-Hiles** [comment]
> Forgive me, this is mostly a copy/paste from my feature Request for element-android.
> #### Description
> 
> In Android 12, Google has added support for Material You, which automatically picks colors for apps/settings/notifications based on your home wallpaper.
> 
> https://www.xda-developers.com/material-you/
> #### Describe the solution you'd like.
> 
> For FluffyChat to support Material You on Android 12.
> #### Describe alternatives you've considered.
> 
> No alternatives.
> #### Additional context
> 
> Google has not yet published third-party docs on how to accomplish this, but several apps have already reverse-engineered support on their own.
> 
> https://www.xda-developers.com/the-first-apps-using-material-you-theming-are-here/amp/
> 
> There is also a library that can be packaged into an app.
> 
> https://www.xda-developers.com/android-12-material-you-dynamic-theming-library/
> 
> https://github.com/KieronQuinn/MonetCompat
> 
> It also sounds like Flutter's SDK will be ready for this in short order.
> 
> https://9to5google.com/2021/05/20/flutter-sdk-material-you/
> 
> /issue fluffy

Can this be reopened? I know you can have material you accents but I'd love a full material you theme with the background and everything. You can use https://pub.dev/packages/dynamic_color.

**Comment by Henry-Hiles** [comment]
@krille-chan please can this be reopened?

**Comment by krille-chan** [comment]
> @krille-chan please can this be reopened?

Why? This is implemented. It has dynamic colors and also colors the background

**Comment by Henry-Hiles** [comment]
> > @krille-chan please can this be reopened?
> 
> Why? This is implemented. It has dynamic colors and also colors the background

Oh, it doesn't color the background for me, only stuff on top of it like FABs. Is this a bug, should I open a new issue?

**Comment by krille-chan** [comment]
it does color the background. You just need to compare it to complete white

**Comment by Henry-Hiles** [comment]
Well I'm in dark mode, but if the accent colours do change the background it's by a tiny amount. Can we have the same background shade as other apps?
