### ISSUE TITLE
Extend your service to Africa especially Nigeria 


### ISSUE THREAD

**Issue by Proudfellow** [krille-chan/fluffychat#1087]
We Have a great p2p trading network of Bitcoiners we love your app so we could use it to connect socially and trade permissionless...

**Comment by AndreasZeissner** [comment]
Hi, 
just stumbled upon this and I am not sure, what you need. 

fluffychat is only a client you might want to have a look at https://matrix.org/.
You should be able to create an account on matrix.org to use fluffychat with it.

For advanced setups you should consider deploying your own federation.

Regards

**Comment by Mikaela** [comment]
I am going to assume this is spam unless more information is provided. FluffyChat doesn't provide any servers.
