### ISSUE TITLE
Cleared messagebox on device rotation

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#111]
#### Description
When typing a message in a room and rotating the device to landscape mode (or vice versa) mid message before sending it, the textfield is cleared in both views. I don't think this is the intended behaviour.

#### To Reproduce
see above

#### Additional information:
- Device: Samsung Galaxy S10+
- OS and OS version: Android 11
- Installed version of FluffyChat: 0.35.0
- (Android only) Which store are you using: F-Droid
- (Android only) Are Google Services available: to some degree

**Comment by schmittlauch** [comment]
Cannot reproduce this anymore in 1.13.0 (Android), it possibly has been resolved together with #511?
