### ISSUE TITLE
FormatException: Unexpected character on login

### ISSUE THREAD

**Issue by m00nwtchr** [krille-chan/fluffychat#1114]
### Bug Description

When I try to log in to my self-hosted homeserver (uses `conduwuit`), the app throws an error. Oddly enough, it seems that a session does still get created on the server. Also the homserver name resets to `null`

### Steps to Reproduce

1. Attempt to login
2. See exception

### Expected Behavior

Login

### App Version

1.20.0

### Additional Platform Information

Android

**Comment by krille-chan** [comment]
Please add more information, like what exception, how does the error look like and get some logs or steps to reproduce
