### ISSUE TITLE
The application does not work, messages do not arrive.

### ISSUE THREAD

**Issue by Olivarew** [krille-chan/fluffychat#1118]
### Bug Description

The application is not working. Lately it has been loading constantly and for a very long time. After downloading, you don’t see when someone writes because the messages don’t arrive. Both mine and my interlocutor’s. I couldn’t go to chats all day to chat because of this problem.

### Steps to Reproduce

?

### Expected Behavior

?

### App Version

V1.20.0

### Additional Platform Information

Doesn't work on iPhone and Android

**Comment by krille-chan** [comment]
Hey, thanks for opening the issue. Sorry to hear, that you have such problems. As this is not clear enough, I would close this for now. Please reopen the issue with more information and clear steps to reproduce.
