### ISSUE TITLE
The flatpak is completely broken

### ISSUE THREAD

**Issue by shellheim** [krille-chan/fluffychat#1123]
### Bug Description

On updating the flatpak to version `1.19.2` and launching fluffychat and then closing and then finally reopening it results in the error : 

```
Unable to build the SQlite database. The app tries to use the legacy database for now. Please report this error to the developers at https://github.com/krille-chan/fluffychat/issues/new. The error message is: SqfliteFfiException(sqlite_error: 26, , SqliteException(26): while selecting from statement, file is not a database, file is not a database (code 26)
Causing statement: PRAGMA user_version}) DatabaseException(SqliteException(26): while selecting from statement, file is not a database, file is not a database (code 26)
Causing statement: PRAGMA user_version) sql 'PRAGMA user_version' {details: {database: {path: /home/shell/.var/app/im.fluffychat.Fluffychat/data/fluffychat/FluffyChat linux.sqlite, id: 1, readOnly: false, singleInstance: true}}} 

```
with the headline : `An error occurred while init the app`

This error results in the user being thrown back to the login page and being unable to login. The issue seems similar to #972.

### Steps to Reproduce

1. Install the version `1.19.2` of fluffychat
2. Login to your matrix account
3. Close fluffychat
4. Re-open fluffychat and observe the error

### Expected Behavior

1. Install fluffychat as flatpak and open it
2. Close fluffychat and re-open
3. The app should be at the same state as before with the user logged in.

### App Version

1.19.2

### Additional Platform Information

Linux 6.8.9

### Additional Context

Is this caused by the flatpak not being synced with the main repo?

**Comment by shellheim** [comment]
[Screencast_20240520_120109.webm](https://github.com/krille-chan/fluffychat/assets/116480892/6b07ded8-7b45-4b88-a595-70f52b2e6873)

**Comment by TGRush** [comment]
Sorry that you're experiencing this, this is a known issue with the Flatpak as it cannot properly communicate with the secrets daemon on the host (Plasma luckily informs you about this), and as such it falls back to a less secure database.

This is an unsolved issue, which is also why updates on the Flatpak are paused.

If it doesn't trouble you too much, I recommend grabbing the latest GitHub release and using that for now!

**Comment by shellheim** [comment]
Man, I just switched from all the app hassles to `https://app.element.io/` in my browser.

**Comment by krille-chan** [comment]
> This is an unsolved issue, which is also why updates on the Flatpak are paused.

I'm not aware that updates on Flatpak are paused. Why has v2.20 not been released to flathub yet?

**Comment by cyrneko** [comment]
> > This is an unsolved issue, which is also why updates on the Flatpak are paused.
> 
> I'm not aware that updates on Flatpak are paused. Why has v2.20 not been released to flathub yet?

Well I assumed it was because Flatpak builds are broken, evident by the current 1.19 build on Flathub constantly falling back to the legacy database and not storing logins.

I'll collect some more info on that if needed

**Comment by cyrneko** [comment]
FYI with the 1.20 release this issue persists.

![image](https://github.com/krille-chan/fluffychat/assets/58338843/16c076b8-b41b-4220-93ad-d8cb39112e2a)

**Comment by jolichter** [comment]
Hi, unfortunately the same issue, so I'm using Element on Manjaro again.

**Comment by shellheim** [comment]
fixed with the newest version for now.
