### ISSUE TITLE
questions about sticker things

### ISSUE THREAD

**Issue by chocosobo** [krille-chan/fluffychat#1127]
Hi, first of all i'm almost new to matrix, not a programmer.
Questions below might fool and weird thing.

As far as I understand Matrix and fluffychat sticker,
fluffychat custom stickers are only can be uploaded on matrix server not external file hosting
type as m.sticker

Questions are
1. Custom stickers with external hosted url is gonna happen?
- to host room and media in seperated servers

2. It might more like Matrix question. Can I restrict user to only use stickers setted up by admin for room but no media uploads?
I'm not sure upload media and m.sticker are different in system
Matrix room setting looks not distinguish text and media

**Comment by krille-chan** [comment]
Hey, thanks for opening the issues. I would kindly ask you to not use issues to ask questions and instead ask the community. Thank you very much
