### ISSUE TITLE
linux build: black screen

### ISSUE THREAD

**Issue by throwException** [krille-chan/fluffychat#1131]
### Bug Description

The screen went black as soon as the initial dialogs (connect, cross signing) were done.

Also, the following exception appeared in console as soon as I pressed any key:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      _isPressed.<anonymous closure> (package:keyboard_shortcuts/keyboard_shortcuts.dart:51)
#1      WhereIterator.moveNext (dart:_internal/iterable.dart:451)
#2      _isPressed (package:keyboard_shortcuts/keyboard_shortcuts.dart:55)
#3      _KeyBoardShortcuts.listener (package:keyboard_shortcuts/keyboard_shortcuts.dart:135)
#4      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:872)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1161)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:235)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:581)
#8      _invoke2 (dart:ui/hooks.dart:344)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45)
#10     _Channel.push (dart:ui/channel_buffers.dart:135)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:343)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:257)
```

### Steps to Reproduce

1. build 1.20.0 for linux
2. run the bundle on linux
3. connect to a homeserver
4. complete the cross-signing dialogs

### Expected Behavior

The chats should appear

### App Version

1.20.0

### Additional Platform Information

x86_64, debian 12 bookworm

**Comment by throwException** [comment]
When run using `flutter run`, 1.20.0 shows a black screen on start, but shows chats on the first keypress.

**Comment by fusion44** [comment]
I have the same problem on NixOS. Screen remains black. I do not get any error messages in the console, though. I've searched the Flutter repository for similar errors, but looks like no one else has this problem.

**Comment by krille-chan** [comment]
That bug came with the new flutter version. However you can just use the stable channel (which you should use anyway)

**Comment by throwException** [comment]
> That bug came with the new flutter version. However you can just use the stable channel (which you should use anyway)

I had to go back to flutter 3.19.6 to build a working version of fluffy 1.20.0.

**Comment by Packbat** [comment]
I suspect I just ran into the same bug after updating NixOS to 24.05 - an additional observation if it is helpful: the contents reappeared if I opened a chat or hovered over the button in the top left corner. Here's a short recording of the settings screen showing off the behavior I observed.

https://github.com/krille-chan/fluffychat/assets/11142302/013aad8c-1abc-404a-b3d4-f2fa78a00b4f

**Comment by crabdancing** [comment]
Same deal here. Also using NixOS 24.05 & Plasma 6.

**Comment by anlumo** [comment]
I'm seeing the same thing on ArchLinux, Fluffychat-localflutter 1.21 with Flutter 3.22.2. Blindly selecting a chat in the sidebar fixes it, but only until the next restart.

**Comment by krille-chan** [comment]
This is fixed in newest version when building with flutter 3.24.1
