### ISSUE TITLE
App Locking issue

### ISSUE THREAD

**Issue by Matt7393** [krille-chan/fluffychat#1157]
### Bug Description

After inputting my code (with app lock) FluffyChat won’t let me in with the correct code.

### Steps to Reproduce

Download Fluffy Chat for IOS
Login and enable app lock
Try to enter correct code

(Note only tested on my iPhone 11)

### Expected Behavior

I input the correct code and it lets me inside like it did prior to this new update.

### App Version

1.21.0

### Additional Platform Information

Device: IPhone 11

### Additional Context

Occurred after my phone automatically installed the new update.

**Comment by krille-chan** [comment]
I'm so sorry that this happened. I have tested app lock on iOS... but actually I used my iPad for testing which **has** a done button on the OSK, while the iPhone don't have it anymore for some reason. That's why this got missed. Will fix it asap and release a hotfix

**Comment by Matt7393** [comment]
Thank you so much, I can verify that the app is now locking again correctly on my iPhone 11!

**Comment by leematos** [comment]
Can confirm as well, fixed for me 👍
