### ISSUE TITLE
Wrong orientation for images

### ISSUE THREAD

**Issue by BhasherBEL** [krille-chan/fluffychat#1168]
### Bug Description

When I send a picture from my galerie, the preview and the final image are rotated by 90°, while the original image is not. When I share the same image from my galerie into fluffy, the orientation is the right one. Element also took the right orientation.

Surprinsingly, screnshots don't have that issue. 

Here is an exemple of a picture with this issue.
![2024-06-08-18-52-43-680](https://github.com/krille-chan/fluffychat/assets/45831883/0766769d-9147-474c-80fe-de9d6618ebf4)

### Steps to Reproduce

1. Take a picture out of fluffy
2. Click on "Send image"
3. Select the picture taken
4. It will be rotated

### Expected Behavior

The picture should keep it original orientation

### App Version

1.20.0

### Additional Platform Information

Android LineageOS, android 13

**Comment by q234rty** [comment]
It seems that this only happens when the image has the "orientation" field in its EXIF metadata?
