### ISSUE TITLE
Android app is not running in debug mode

### ISSUE THREAD

**Issue by adar2378** [krille-chan/fluffychat#1174]
### Bug Description

Receiving this error when building android app in debug mode:

* What went wrong:
Could not determine the dependencies of task ':unifiedpush_android:compileDebugKotlin'.
> Unable to download toolchain matching these requirements: {languageVersion=8, vendor=any, implementation=vendor-specific}
   > Unable to download toolchain. This might indicate that the combination (version, architecture, release/early access, ...) for the requested JDK is not available.
      > Could not read 'https://api.adoptopenjdk.net/v3/binary/latest/8/ga/mac/aarch64/jdk/hotspot/normal/adoptopenjdk' as it does not exist.

### Steps to Reproduce

- git clone https://github.com/krille-chan/fluffychat.git
- cd fluffychat
- git apply ./scripts/enable-android-google-services.patch
- Install CMake from the SDK Manager (installed 3.18.0 and also 3.22.1)
- `flutter run` for android simulator

### Expected Behavior

The app should run in debug mode in emulator.

### App Version

1.21.0+3533

### Additional Platform Information

Pixel 6A emulator Android API 34

### Additional Context

Flutter doctor output:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.2.1 23C71 darwin-arm64, locale en-BD)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.89.1)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!

My java version:

openjdk 17.0.9 2023-10-17
OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
OpenJDK 64-Bit Server VM (build 17.0.9+0-17.0.9b1087.7-11185874, mixed mode)

Note: I am using FVM to support flutter 3.22.2 due personal reason.

**Comment by biowilli** [comment]
I have the same issue.

**Comment by adar2378** [comment]
@biowilli Just install java 8 on your machine.
