### ISSUE TITLE
Support for multi-account push notifications on iOS

### ISSUE THREAD

**Issue by ethanaobrien** [krille-chan/fluffychat#1178]
### Feature Description

The ability to have push-notifications for multiple accounts on iOS would be nice. At the moment, only the first account you sign in to have push notifications turned on. Going to Settings > Notifications > Devices will show your fluffychat iOS client for the first account you sign into, though not for any other accounts.

To add, if you delete your push notification settings under Settings > Notifications > Devices, then clicking your client and pressing "delete", you will have no option to move it to another account, or re-enable it. You must delete and re-install the app to re-enable push notifications for that account.

### Rationale

I have multiple matrix servers that I would like to get notifications for

**Comment by wrenix** [comment]
Looks like duplicated of #169
