### ISSUE TITLE
Code blockst that are wider than the message bubble can not be scrolled

### ISSUE THREAD

**Issue by tux93** [krille-chan/fluffychat#1195]
### Bug Description

When trying to scroll a code block sideways the view immediately jumps back to the start of the line, making it impossible to read lines that are longer than the width of the message bubble.

### Steps to Reproduce

1. Receive / send a message with a ```code block``` that has lines longer than the width of the message bubble
2. Try to scroll the text in the code block sideways
3. The view immediately jumps back to the start of the line

### Expected Behavior

The view stays at the scroll position and does not immediately jump to the start again.

### App Version

1.21.0

### Additional Platform Information

OnePlus 8, LineageOS 21

**Comment by opk12** [comment]
I can confirm on Samsung Android 7.1, for both block and inline markdown

**Comment by tux93** [comment]
Appears to be fixed in 1.21.1
