### ISSUE TITLE
Key Backup/Restore via File

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#124]
#### Description
To be able to export keys to a password-protected file and import them again would be good.  And if the format was compatible with element's format then that would be very very extra cool.

#### uh, why?
Server based backup/restore is really hit or miss, basically.  Half the time it just doesn't work at all, and you don't get your old messages back, but I think explicitly exporting from one session and importing into other session is more explicit and more fool-proof.

Also I've heard some people would rather manage their own key backups than let the server do that.  Maybe for security reasons or maybe because it seems easier.

**Comment by heylix** [comment]
That would be awesome. I currently have an issue where I can't sync with the server, so I'd really like to import the room keys I exported from Element. Nheko can also already import and export keys, so if you implement this feature it'd be nice if you could test it with Element and Nheko as sources and targets just to be sure it works.

Thank you for your great work, btw :)

**Comment by tasmo** [comment]
This is a real blocker. I like FluffyChat on mobile but not on Desktop. To get the old messages decrypted on a different client the encryption keys are needed as a file.

**Comment by jahway603** [comment]
FluffyChat is an amazing client, but I've had friends try it and then move away from it because this feature is missing. Any ideas on how to implement this?

**Comment by berlincount** [comment]
I'm affected by this issue as well. (Re-)Pushing existing keys to the SSSS doesn't seem to be happening, either, so there is no recourse for me.
