### ISSUE TITLE
Auto log out. Error: old database type.

### ISSUE THREAD

**Issue by SpiritOTHawk** [krille-chan/fluffychat#1268]
### Bug Description

Sometimes when i lauch fluffychat, log out of all accounts (2 using). And gives an error: old database type.

### Steps to Reproduce

1. Install LM 22 and fluffychat
2. Log in
3. Use app sometime

### Expected Behavior

All works fine

### App Version

1.21.1

### Additional Platform Information

Linux Mint 22 (Ubuntu 24.04)

### Additional Context

Using app from flatpak

**Comment by compuguy** [comment]
Having the same issue with the flatpak, 1.21.1, on RHEL 8. Though I didn't log out of any of my accounts, the error occurred on startup.

**Comment by SpiritOTHawk** [comment]
@krille-chan

**Comment by SpiritOTHawk** [comment]
The problem no longer exists on LM 22. Fluffychat 1.22.0.

**Comment by krille-chan** [comment]
> The problem no longer exists on LM 22. Fluffychat 1.22.0.

Thanks, I would then close this as fixed. Please reopen if it happens again on newer versions
