### ISSUE TITLE
Japanese keyboard doesn't work on Android

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#130]
#### Description
The way Japanese input works is you first enter a word's pronunciation, and then you choose how the actual word is written. However, in FluffyChat, said selection immediately closes after appearing, rendering Japanese input unusable.

#### To Reproduce
- Install Mozc for Android
- Try using it (compare with how other apps handle it if necessary)

#### Additional information:
- Installed version of FluffyChat: 0.38.0
- (Android only) Which store are you using: F-Droid
- (Android only) Are Google Services available: microG

By the way, another related annoyance of mine that I don't feel like reporting separately (but maybe I should) is how instead of a full cursor with a text select "handle" only a regular line cursor is shown in most cases, making going to the message start very inconvenient, as you can accidentally hit the encryption settings button.

**Comment by kuon** [comment]
I have the same issue. I'd happily help debug it. The issue is not present with gboard, only mozc.
