### ISSUE TITLE
Fwd: FluffyChat Android doesn't seem to render RTL and LTR text right

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#132]
'-------- Välitetty viesti / Fwd.Msg --------
Aihe: FluffyChat Android doesn't seem to render RTL and LTR text right
Päiväys: Sun, 29 Aug 2021 20:48:08 +0000
Lähettäjä: Jaafar <redacted>
Vastausosoite: Jaafar <redacted>
Vastaanottaja: redacted

I'm in an Arabic room where we sometimes use English in the middle of 
the sentence. Arabic is written RTL, and English LTR. The problem is 
that, on FluffyChat, these kinds of messages are completely unreadable 
and sentences are scrambled all over the place.

Here's an image that showcases the mess that occurs when writing English 
and Arabic together in FluffyChat:

![broken_arabic](/uploads/8b379c0f4001e8724d8b820a1292b465/broken_arabic.png)

[OpenPGP_0x99392F62BAE30723.asc](/uploads/b8e222bf8d2baf53a59cb7634363a211/OpenPGP_0x99392F62BAE30723.asc)

**Comment by Mikaela** [comment]
Duplicate of #63.
