### ISSUE TITLE
Startup consistently takes a very long time

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#136]
#### Description
Starting FluffyChat consistently takes very long for me. I timed a few startups today and all attempts took about 40 seconds (from tapping the app icon to when the chat list is shown, although sometimes syncing still takes some more time after the room list is shown).

#### Additional information:
- Device: Fairphone 3
- OS and OS version: LineageOS 18.1 (no gapps, microg installed)
- Installed version of FluffyChat: Latest nightly from the fluffychat nightly f-droid repo (always on the newest monthly, and this has stayed the same at least for some months)

**Comment by OE1KHZ** [comment]
Having the Same issue here. 10sec startup time.

- Device: OnePlus 8T
- ROM: CrDroid 10.4 (microg installed)
- Bug present on every version (via f-droid repo) since I have this app (abt 8 months).

App starts way faster (under a sec) as soon as I get a notification that I have received a new message.

**Comment by devurandom** [comment]
I still habe this problem with FluffyChat 2.0.0 on Android 13 on a Fairphone 3. Startup is very slow and takes a minute up to multiple minutes on the "FluffyChat icon page", until it even shows the chat list and "waiting for server" and then "synchronising".

**Comment by Septicity** [comment]
Issue replicated on FluffyChat 2.0.0. It takes around 2 minutes to start the app, and it claims that the app is Not Responding while it loads.

Device: Moto G Power (2021)
OS: LineageOS 22.2 (Android 15)
RAM (not a typical device spec to list for phones, but may be relevant here): 3 GB

I'll include the verbose logs from what I assume is the app launching:
```
# [ERROR] Error during processing events - TimeoutException after 0:00:10.000000: Future not completed
#0      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:1045)
<asynchronous suspension>
#1      Client._innerSync (package:matrix/src/client.dart:2353)
<asynchronous suspension>
#2      Client._sync.<anonymous closure> (package:matrix/src/client.dart:2245)
 <asynchronous suspension>
```

**Comment by devurandom** [comment]
The issue persists with FluffyChat 2.3.1 on Android 13 on Fairphone 3.

**Comment by trymeouteh** [comment]
I have this issue as well with the FDroid version of the app on LineageOS with or without unified push
