### ISSUE TITLE
E2EE unusable due to cloud backup unlock  broken

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#137]
#### Description
Since a recent update, the E2EE became unusable due to cloud backup unlock now being broken. See the steps to reproduce.

#### To Reproduce

1. Have an account with E2EE cloud backup, possibly needs to be on `matrix.org` homeserver
2. Uninstall fluffychat flatpak if present, and wipe `~/.var/app/im.fluffychat.Fluffychat` (**deletes all your session data!!!!**)
3. Reinstall fluffychat flatpak
4. Login
5. Go to Settings > Security and the Cloud backup button. Since this is a fresh session, it should show cloud backup currently being off.
6. Hit cloud backup and wait for prompt to enter your backup restore password
7. Enter your cloud backup restore password

--> "Oops, something went wrong..." every single time. All DMs remain encrypted even though it claims cloud backup is on after, so clearly it didn't work.

#### Additional information:
- Device: PinePhone
- OS and OS version: Mobian bookworm 
- Installed version of FluffyChat: latest arm64 flatpak
- (Android only) Which store are you using: 
- (Android only) Are Google Services available:

**Comment by Lunaphied** [comment]
Having this on the iOS App Store version on an iPhone 15 and iOS 17, also happened on previous iPhone 13. 

Syncing with another device seemed to work, but that's not always an option and sometimes that's broken too

**Comment by Lunaphied** [comment]
What no this is still relevant
