### ISSUE TITLE
[Feature Request] Android Auto support

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#14]
#### Description
There is currently no Matrix-client with Android Auto support.  Android Auto isn't perfect, but communication apps (Signal, Google Messages, WhatsApp) that make use of it are great and easy to use.

#### To Reproduce
Nothing to reproduce.

#### Additional informations:
- Device: Pixel 4 XL
- OS and OS version: Android 11
- Installed version of FluffyChat: 0.19.1
- (Android only) Which store are you using: Play
- (Android only) Are Google Services available: Yes

**Comment by strk** [comment]
Why is this closed as not planned ? I see android auto support exists as of today 🤔
