### ISSUE TITLE
m.sticker missing info

### ISSUE THREAD

**Issue by North-West-Wind** [krille-chan/fluffychat#1454]
### Bug Description

Stickers sent from FluffyChat has an empty `info` object. Normally this would be fine, but it breaks with the Mautrix Discord bridge. Missing mimetype (maybe width and height as well) causes the bridge to not realize it's an image.

On FluffyChat:
![Screenshot of FluffyChat](https://github.com/user-attachments/assets/23c62871-7f4a-4c61-b967-35dc7afa0316)

On Discord:
![Screenshot of Discord](https://github.com/user-attachments/assets/a077494a-0c53-4ea7-b016-84f005c83b76)

### Steps to Reproduce

1. Add a sticker to FluffyChat
2. Send a sticker
3. Select the message and check message info
4. The `content.info` field is an empty object

### Expected Behavior

The `content.info` should have metadata about the file. For example, Cinny includes this:
![Cinny m.sticker includes info](https://github.com/user-attachments/assets/036be15f-d8d1-40cd-9788-3677eb1d06bf)

### App Version

1.22.0

### Additional Platform Information

OS: Android

**Comment by krille-chan** [comment]
FluffyChat adds metadata from stickers, but the data needs to be configured correctly in the given sticker pack. FluffyChat does this when importing a sticker so this is a problem with your sticker import 🤔

**Comment by North-West-Wind** [comment]
I see. I have been reading the MSC2545 proposal and missed that part. Thanks!
