### ISSUE TITLE
support for RTL Languages

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#157]
#### Description
Hello, please support right-to-left languages, for example Persian is very well supported, but due to the left-to-right environment of FluffyChat, the texts of right-to-left languages are displayed in a disordered way like Persian.

The simple solution is to create an option in the FluffyChat settings that moves the matrix texts right to left.

#### Additional information:
- Device: Ubuntu20.04 , Android 11(custom rom _AOSP)
- OS and OS version: 
- Installed version of FluffyChat: 0.40.1
- (Android only) Which store are you using: f-droid
- (Android only) Are Google Services available: No

**Comment by Mikaela** [comment]
Duplicate of #63.
