### ISSUE TITLE
Multi-account randomly makes accounts disappear and after relogging in, key backup won't work with m.invalid_message

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#165]
#### Description

When multiple accounts are added to FluffyChat, sometimes they just disappear without a trace requiring logging in again. Later they cannot be verified for key backup either by entering key or transferring from another device as error `m.invalid_message` happens.

#### To Reproduce

1. Login to FluffyChat
2. Add another account from settings
3. Add a couple of more accounts
4. Use FluffyChat normally
5. Notice that at some point some accounts are gone. It may or may not be related to poor network like when leaving building, and opening or closing FluffyChat, entering metro/underground WiFi network or similar.

#### Additional information:
- Device: iPhone SE2020 / A2296
- OS and OS version: iOS 15.0.1 (19A348)
- Installed version of FluffyChat: 0.41.2

**Comment by Damaj301damaj-lol** [comment]
I just updated my android version of fluffychat and this happened as well, rip my accounts :(
