### ISSUE TITLE
[Bug/Improvement] search filter on forwarding

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#17]
#### Description
Forward UI have to be reset or better searchable in contact list.

#### To Reproduce
1. Search a Chat
2. Forward a Message
3. only searched Chats will appear

#### Additional informations:
- Device: Huawei Mate 20 Lite
- OS and OS version: 10
- Installed version of FluffyChat: main
- (Android only) Which store are you using: yes
- (Android only) Are Google Services available: yes

**Comment by ZenKyma** [comment]
Can confirm that the issue still persists in Android v1.13.0.

**Comment by ZenKyma** [comment]
Still relevant und unresolved
