### ISSUE TITLE
Android SAML login does nothing

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#171]
#### Description
In the Android version, when trying to sign into a server that exclusively uses SAML (eg, https://mozilla.org), a "Sign In with SAML" button appears but tapping appears to do nothing.

#### To Reproduce
- Enter https://mozilla.org as your homeserver (or https://chat.mozilla.org)
- Tap Sign In with SAML

#### Additional information:
- Device: Samsung Galaxy Note 10+
- OS and OS version: Android 11
- Installed version of FluffyChat: 0.41.4
- (Android only) Which store are you using: Play Store
- (Android only) Are Google Services available: Yes

**Comment by mohammadRezaeian** [comment]
hi
after i change permission to access phone i can login to mozilla account 

OS and OS version: Android 12 DivestOS
Installed version of FluffyChat: 1.13.0
(Android only) Which store are you using: F-Droid
(Android only) Are Google Services available: No
