### ISSUE TITLE
Media files in gallery app (android)

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#174]
#### Description
As a normal user, I expect that media files like photos or videos I received are visible in the gallery app on android devices. I supposed in iOS should be the same.

The current behaviour seems that the file is kept inside the application in the storage and the user has no possibility to remove it without removing the message. That could propitiate storage problems when you have used the app for a long time and you receive a lot of media files every day.

**Comment by LFd3v** [comment]
If this feature is added, please make it optional (disabled by default) with a setting to toggle it on/off. Actually most messengers do this to avoid cluttering the device gallery and for privacy.
