### ISSUE TITLE
Unable to change order of spaces in the list

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#208]
#### Description
It seems to be impossible to reorder the spaces. If it's somehow possible, the location of the option should be in a much better place, as I've been looking for 30 minutes for an option.

#### Additional information:
- Device: Pixel 4a5g
- OS and OS version: LineageOS 18.1
- Installed version of FluffyChat: 1.0.1
- (Android only) Which store are you using: fdroid probably
- (Android only) Are Google Services available: yes

**Comment by goose121** [comment]
It would be really nice if this was a feature; unsure if the issue getting closed was because it's not wanted or because it got forgotten about? This is a feature Element has, btw.
