### ISSUE TITLE
[Localization] Element is apparently internally telling everyone that Spaces are a name like Matrix Spaces and should always be written with capital letter and never translated.

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#244]
#### Description

I think consistency is needed and FluffyChat should follow that.

For example currently FluffyChat Finnish calls Spaces as "Avaruus" which are spaces with stars within them<small>, and Element Web calls Spaces as "välilyönti" which is space(bar)</small>

I think they currently exist in FluffyChat also with a small letter.

![1](https://matrix-client.matrix.org/_matrix/media/r0/download/maunium.net/gcPxELTETKwafIoVzFWWTUsx)
![2](https://matrix-client.matrix.org/_matrix/media/r0/download/maunium.net/cuYPXYRHdDCxUeqGVTmMnQkl)
![3](https://matrix-client.matrix.org/_matrix/media/r0/download/maunium.net/yVsgeuuTNNsXhbkmFWORexsl)

* > [1](https://matrix.to/#/!yvhoprZiKmhjxKfNHa:matrix.org/$DuCc9glX7WERvhcPrmdM1gjvLybGgo_YcrgWdZg_L_I?via=matrix.eclabs.de&via=matrix.org&via=tchncs.de), [2](https://matrix.to/#/!yvhoprZiKmhjxKfNHa:matrix.org/$jQn3fUUe4Fma2hK3ucdxTvkbnMHbYDsrRcNeYXBue3M?via=matrix.eclabs.de&via=matrix.org&via=tchncs.de), [3](https://matrix.to/#/!yvhoprZiKmhjxKfNHa:matrix.org/$EWqyd2z3ZlJgkNK-3fi9KG_HS3ewYeoMeKPBrAfD4k4?via=matrix.eclabs.de&via=matrix.org&via=tchncs.de)

<small>Screenshots and links stolen from @tulir</small>

Also discussed in translations room: https://matrix.to/#/!ktZyBKHOnKWNhjWWKx:sorunome.de/$pfzUAMuHPFSq-C4J-eATL1UNq5SosHMILzBXIUJTutw?via=janian.de&via=matrix.org&via=luckyskies.pet

**Comment by Mikaela** [comment]
Finnish has switched to _tila_ as in _[Work]space_ and this issue is useless without the comments lost at GitLab.
