### ISSUE TITLE
No connection to my own server

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#246]
#### Description
Cant connect to my own server in my private network

#### To Reproduce
I am writing to "Server Matrix" URL of my own server, for example "matrix.shmelovod.ru".
Error: "No connection to the server". But in browser web-page of this URL have been opened.
(DNS-record there is, but server not trusted by matrix, because in my private network. Access via VPN)

#### Additional information:
- Device: Iphone 12
- OS and OS version: IOS 15.1.1
- Installed version of FluffyChat: 1.1.0
- (Android only) Which store are you using: 
- (Android only) Are Google Services available:

**Comment by ildar** [comment]
please reopen
