### ISSUE TITLE
[Feature Request] Allow copy-pasting of images/other media in Desktop version of app

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#25]
Other chat apps like Discord, Signal, Element, etc., allow me to copy paste an image in my clipboard and it will start to upload it or allow me to type a caption before finishing the upload. This is really great for quick image searching where the user doesn't need to download the app, open the upload widget, find the file, and then upload the image. All while leaving a potentially unwanted image on the users computer when finished.

If this is a feature and I am experiencing a bug, I am on Nixos Unstable, installing the app as a flatpak from Flathub.

**Comment by PgBiel** [comment]
This (not being able to paste images) seems to affect all platforms (mobile and desktop), and seems to be an upstream issue: https://github.com/flutter/flutter/issues/23603

In that issue, it was mentioned that a third-party plugin for flutter was created to tackle this problem: https://pub.dev/packages/super_clipboard

This seems to have been adopted by other flutter apps, e.g. https://github.com/LinwoodDev/Butterfly/issues/422

Perhaps that plugin could be used for FluffyChat as well? What do you think?

And, if that seems OK, would you be looking for a contribution to implement that? (Perhaps someone can step up to help?)

**Comment by k3-cat** [comment]
I guess we can add a button to the long-press menu (or an entery in the "plus sign menu") to get images and rich texts from clipboard using `super_clipboard`?

If that is OK, I can do the code.
