### ISSUE TITLE
Possible bug with sync/presence logic

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#266]
#### Description
It seems like that fluffychat has some kind of bug with how m.presence is set. Opening the app seems to cause spikes on m.presence as well as the sync endpoint. (In the area of 100Hz which is well outside sensible numbers)

See blue spikes. Those happen each time I open fluffy:
![image](/uploads/b10c99cb359a1e9ef2bc57da60868a10/image.png)

I am assuming this is either caused by Fluffy having a bug in the sync logic itself for either general sync or sync in notifications, or it is fighting over presence with another client.

#### To Reproduce
I currently have no proper way of reproducing this. I am assuming however, setting a presence via element-web likely could cause this.

#### Additional information:
- Device: One Plus 7 Pro
- OS and OS version: Android 11
- Installed version of FluffyChat: latest nightly (at this time commit de7e678962e506b68d0e8264908c7b25a4957d4d)
- (Android only) Which store are you using: Fdroid nightly
- (Android only) Are Google Services available: yes

(Labelled as medium as this seems to cause extreme battery drain which isn't nice for users and also may affect famedly users if my assumption turns out to be true and also happens in famedly. It is unconfirmed at this time though.)

**Comment by kputh** [comment]
It probably has nothing to do with this issue, but: it seems like FluffyChat frequently creates new Futures for [FutureBuilder](https://api.flutter.dev/flutter/widgets/FutureBuilder-class.html) inside of `build()` methods. FutureBuilder's documentation indicates it as an anti-pattern, and I expect it to cause FluffyChat to send more requests than you intend.
