### ISSUE TITLE
Is it possible to use FluffyChat as a library (in another AGPL application...)?

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#296]
Hi, I'm currently developing https://veganbuddies.org/ and I don't want to invest in creating chat components. I was wondering if it would be technically possible to use FluffyChat as a library or if I'll need to fork your project if I want to use FluffyChat's chat components.

Thanks for answering, Tim

**Comment by mthinh** [comment]
@krille-chan any update? Is that possible to make a fork of Fluffy chat and use it as library ?

**Comment by krille-chan** [comment]
Sorry, I can not give legal advice as I am not a lawyer. Please investigate this by yourself. Thank you so much
