### ISSUE TITLE
Room images in SVG format not displayed

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#299]
#### Description
I have set room images for some of my spaces (with a different client). Some of them are PNGs and some of them SVGs.
Fluffychat successfully displays the images that are in PNG format, but not the SVGs.

#### To Reproduce
Set a room image in SVG format and check how it's being displayed.

#### Additional information:
- Device: Pixel 3a
- OS and OS version: Android 12
- Installed version of FluffyChat: 1.2.0
- (Android only) Which store are you using: F-Droid
- (Android only) Are Google Services available: yes

**Comment by AsenHu** [comment]
Is there any hope for this issue to be resolved 🥲

I'm using an avatar generator, but it can only generate svg avatars. So it would be very useful if fluffy could show the svg avatar.
