### ISSUE TITLE
Video playback does not stop, Sound is still playing

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#309]
#### Description

Video playback does not stop, i.e. Sound is still playing

#### To Reproduce

If I start a video from the chatlist in a room it keeps getting played (as in < v1.3) even though I clicked back, i.e. I can still here the sound. If I press `Home` button it stops but immediately after I open FC again the sound is back too. If I then go into the room where I initially started the video it is shown as "not downloaded" while I can still here it playing! https://fluffychat.im/web seems not affected: the video (sound) immediatelly stops if I switch to another room.

![2022-02-12-18-45-19](/uploads/c683f7923c823fd4931e3aaeb89d8ee4/2022-02-12-18-45-19.png)
This is what I mean with "_Not downloaded_"

#### Additional information:
- Device: S4mini (LOS17), OnePlus 3T (LOS18)
- Installed version of FluffyChat: 1.3
- (Android only) Which store are you using: F-DROID
- (Android only) Are Google Services available: OP3T:YES, S4MINI:NO![2022-02-12-18-45-19]

**Comment by jtrees** [comment]
I just ran into this on 2.0.0.

Request re-opening.
