### ISSUE TITLE
Hitting Enter when prompted to autocomplete a username sends the incomplete message instead

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#320]
I tried to search the issue tracker with similar keywords and found nothing; hope this isn't a dupe.

#### Description

If I'm in a Matrix room where there's a user `@foobar` and I start a message with `@foo`, the UI shows a pop-up suggesting to autocomplete the username. If I then press the Enter key, as I would do on most other chat apps (Slack, Discord, Telegram, ...), it instead sends the incomplete message.

Worth noting that the Element Matrix client had this bug for a long time as well; see https://github.com/vector-im/element-web/issues/15646

#### To Reproduce

See the above. I don't think anything else is required to reproduce, but am happy to provide more details if needed.

#### Additional information:
- Device: A p14s gen2 laptop
- OS and OS version: Arch Linux, with kernel 5.16, running sway (Wayland)
- Installed version of FluffyChat: 1.2.0
- (Android only) Which store are you using: 
- (Android only) Are Google Services available:

**Comment by Kagee** [comment]
This also happens on Android. Can not use enter to autocomplete, can not touch UI popup to autocomplete.

Tested on Android 13 and 14. Installed from Google Play.

**Comment by Fabian42** [comment]
Newer issue for this: #943
