### ISSUE TITLE
Make default screen "All chats" work like "Home" screen on Element client

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#329]
#### Description
I would appreciate at least having the option to hide all rooms and chats that are already in some Space like Element client does with "Home" page.

#### To Reproduce
- Open FluffyChat on Android

**Comment by PhieF** [comment]
I guess it should even be the default behavior, when joining lots of spaces element is such a mess :D

**Comment by Riesi** [comment]
Hey!

I think this would still be a very good feature and default.
Right now my "All" is cluttered with too many chats that are from some spaces. 

Thanks :)
