### ISSUE TITLE
Feature: Image gallery in chats

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#342]
_This is a request from a playstore review. I am just moving it here to have it in the right tracker_
#### Description
A WhatsApp like gallery to see media inside fluffy.

**Comment by wcjord** [comment]
@krille-chan are you interested in doing this? @ggurdin could help with it.

**Comment by LFd3v** [comment]
This would be a great feature! Or, at least, allow browsing to next/previous image in the room without closing the image viewer.

**Comment by krille-chan** [comment]
Has been implemented now but needs some polishing before release

**Comment by mokkun** [comment]
@krille-chan was this ever released? I've noticed while using the app that uploading multiple images at once does not group them in a gallery. 🥲

**Comment by krille-chan** [comment]
> [@krille-chan](https://github.com/krille-chan) was this ever released? I've noticed while using the app that uploading multiple images at once does not group them in a gallery. 🥲

Yes when you go on search. Grouping in timeline is something different
