### ISSUE TITLE
Performance issues under GNOME wayland

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#357]
#### Description

Trying to use Fluffychat under GNOME/Wayland (I haven't tried xorg) has performance problems.
The mouse cursor is laggy and none of the animations are smooth. I can also see a spike in CPU usage every time I focus the fluffychat window!

The issue seems to be related to the size of the window. I have two 4k monitors that are powered by an eGPU. My guess would be that the application is for some reason bypassing the GPU and instead renders using the CPU? Not sure if that is a known Flutter issue.

As I decrease the size of the window, things begin to work smoothly!

#### To Reproduce

Install fluffychat and try to use it.

#### Additional information:
- Device: Thinkpad t480
- OS and OS version: Manjaro. Kernal version 5.10.109-1-MANJARO
- Installed version of FluffyChat: 1.4.0
- (Android only) Which store are you using: 
- (Android only) Are Google Services available:

**Comment by Mart-Bogdan** [comment]
Lol. why is it closed? did performance become better?
