### ISSUE TITLE
As i try to run fluffy chat windows client in debug mode, it report an error

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#358]
#### Description

As I try to run fluffy chat in debug mode on windows it report an error

Here is the out put data

PS C:\Users\william\Desktop\fluffychat\fluffychat> flutter run
Multiple devices found:
Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1682]
Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.88
Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.50
[1]: Windows (windows)
[2]: Chrome (chrome)
[3]: Edge (edge)
Please choose one (To quit, press "q/Q"): 1
"ar": 26 untranslated message(s).
"bn": 578 untranslated message(s).
"ca": 109 untranslated message(s).
"de": 13 untranslated message(s).
"eo": 106 untranslated message(s).
"es": 60 untranslated message(s).
"eu": 23 untranslated message(s).
"fa": 558 untranslated message(s).
"fr": 1 untranslated message(s).
"ga": 79 untranslated message(s).
"gl": 1 untranslated message(s).
"he": 249 untranslated message(s).
"hr": 30 untranslated message(s).
"hu": 155 untranslated message(s).
"hy": 302 untranslated message(s).
"it": 117 untranslated message(s).
"ja": 136 untranslated message(s).
"ko": 26 untranslated message(s).
"lt": 548 untranslated message(s).
"nb": 172 untranslated message(s).
"pl": 115 untranslated message(s).
"pt": 583 untranslated message(s).
"pt_BR": 11 untranslated message(s).
"pt_PT": 193 untranslated message(s).
"ro": 552 untranslated message(s).
"ru": 1 untranslated message(s).
"si": 509 untranslated message(s).
"sk": 253 untranslated message(s).
"sl": 446 untranslated message(s).
"sr": 137 untranslated message(s).
"sv": 13 untranslated message(s).
"ta": 580 untranslated message(s).
"vi": 482 untranslated message(s).
"zh_Hant": 130 untranslated message(s).
To see a detailed report, use the untranslated-messages-file
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection>

This will generate a JSON format file containing all messages that
need to be translated.
Launching lib\main.dart on Windows in debug mode...
D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: The command "setlocal [C:\Users\william\Desktop\fluffychat\fluffychat\build\windows\INSTALL.vcxproj]
D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: "D:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake [C:\Users\william\Desktop\fluffychat\fluffychat\build\windows\INSTALL.vcxproj]
D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\Users\william\Desktop\fluffychat\fluffychat\build\windows\INSTALL.vcxproj]
D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: :cmEnd [C:\Users\william\Desktop\fluffychat\fluffychat\build\windows\INSTALL.vcxproj]
D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [C:\Users\william\Desktop\fluffychat\fluffychat\build\windows\INSTALL.vcxproj]
D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: :cmErrorLevel [C:\Users\william\Desktop\fluffychat\fluffychat\build\windows\INSTALL.vcxproj]
D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: exit /b %1 [C:\Users\william\Desktop\fluffychat\fluffychat\build\windows\INSTALL.vcxproj]
D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: :cmDone [C:\Users\william\Desktop\fluffychat\fluffychat\build\windows\INSTALL.vcxproj]
D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [C:\Users\william\Desktop\fluffychat\fluffychat\build\windows\INSTALL.vcxproj]
D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: :VCEnd" exited with code 1. [C:\Users\william\Desktop\fluffychat\fluffychat\build\windows\INSTALL.vcxproj]
Building Windows application...
Exception: Build process failed.
PS C:\Users\william\Desktop\fluffychat\fluffychat>

#### To Reproduce

Follow the instruction in https://gitlab.com/famedly/fluffychat/-/wikis/How-To-Build
As I runing the command "flutter run" and choose 1 for windows client it report this error

#### Additional information:
- Device: Lenovo R9000P
- OS and OS version: Windows 10 Pro 21H2 x86_64 19044.1682
- Installed version of FluffyChat: 1.4.0

**Comment by SingleIssueCoder** [comment]
Hello, 

I had this same issue.

Please try the following steps:

1. Delete CMakeLists.txt from fluffychat/windows
2. Run `flutter config --enable-windows-desktop`
3. Run `flutter clean`
4. Run `flutter create .`

After this, I was able to build without getting those errors.
