### ISSUE TITLE
Support sharing Matrix URI scheme (permalinks to rooms)

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#359]
#### Description

Currently sharing a room shares a `matrix.to` URI including the alias. This is useless when the target homeserver is down.

Earlier in the morning I was attempting to join `#element-web:matrix.org` from `pikaviestin.fi`, while I was able to invite myself from another homeserver, I am unable to interact with the invite due to "oops something went wrong".

What I would like is the ability to share a Matrix URI scheme link pointing to the room iD and at least three vias/homeservers (when they exist) through which the room can be joined, e.g. `matrix:roomid/somewhere:example.org?via=elsewhere.ca` https://spec.matrix.org/latest/appendices/#matrix-uri-scheme

I think it could be even hidden behind long touching of the share room button for picking a `matrix.to` or `matrix:roomid` or `matrix:r` link.

**Alternatively** I could make the Matrix URI scheme links by myself *if* FluffyChat exposed the room internal ID to me without special privileges like Element Web has it in advanced room settings.

#### To Reproduce

1. Join a room on dead homeserver somehow
2. Share the link to the room
3. The target cannot join the room due to the homeserver being down

#### Additional information:
- Device: iPhone SE2020
- OS and OS version: 15.4.1 (19E258)
- Installed version of FluffyChat: 1.4.0 (18
- (Android only) Which store are you using: Testflight
- (Android only) Are Google Services available:

**Comment by bgodlin** [comment]
@krille-chan do you have any plans to resume work on this issue soon? It would help support your use case, and also make quick message link sharing possible.
