### ISSUE TITLE
Allow App Backup

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#367]
#### Description

In the Android manifest, we should set `android:allowBackup` and `android:fullBackupContent` to `true`, as seen in https://gitlab.com/famedly/fluffychat/-/blob/main/android/app/src/main/AndroidManifest.xml#L34 .

This simplifies to move to a new device once the old one is lost or broken.

**Comment by Kobaxidze256** [comment]
OFC matrix crapshitfuck can't do this ONE FUCKING THING right. Can't even delete this garbage without backing up the messages with the braindead idiot who suggested it to me.

**Comment by Kobaxidze256** [comment]
Can you please just do this ONE THING right and let me upgrade my OS.
