### ISSUE TITLE
Use notification channels on Android

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#375]
#### Description

On Android, notifications can be grouped into notification channels. Notification channels can also be conversation notification channels, which are handled slightly differently by android, like showing up at the top. Most messengers use separate conversation notification channels for each conversation or group, like Element or Signal. It would be cool if FluffyChat did the same.

#### To Reproduce

Set up FluffyChat with Ntfy. Receive a message.

#### Screenshots
Here is how I can manage the FluffyChat notifications:
![Screenshot-2022-06-05-17-15-48.jpg](/uploads/c304c6852732c6d7fc426fba3528f542/Screenshot-2022-06-05-17-15-48.jpg.jpeg)

And here it is with Signal:
![Screenshot-2022-06-05-17-15-19.jpg](/uploads/4ad67d2fb7d8717c0eed3643e2927aab/Screenshot-2022-06-05-17-15-19.jpg.jpeg)

#### Additional information:
- Device: Pixel 4
- OS and OS version: Android 12
- Installed version of FluffyChat: 1.5.0
- (Android only) Which store are you using: F-Droid
- (Android only) Are Google Services available: MicroG available, but F-Droid FluffyChat used, so ntfy installed instead

**Comment by Mikaela** [comment]
I think someone was asking about this very recently as everything has its own notification channel without a mechanism to adjust notifications for all rooms or DM rooms at once.
