### ISSUE TITLE
Material You OLED Black theme results in gray background with black message bubbles.

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#376]
#### Description
When using FluffyChat on Android 12, the Material You theme is used. Using an OLED Black Material You theme works properly in most apps, however, FluffyChat uses the wrong color for the background and chat bubbles in the room view.

Room view:

<img src="https://deadca.de/pub/fluffychat_room_view.png" height=400>

Room list:

<img src="https://deadca.de/pub/fluffychat_room_list.png" height=400>

Settings:

<img src="https://deadca.de/pub/fluffychat_settings.png" height=400>

#### To Reproduce
- Set Material You to OLED Black
- Open any room in FluffyChat

#### Additional information:
- Device: OnePlus Nord (avicii)
- OS and OS version: SuperiorOS (Android 12L)
- Installed version of FluffyChat: 1.5.0
- (Android only) Which store are you using: F-Droid, From FluffyChat repo
- (Android only) Are Google Services available: No

**Comment by ek-is-anika** [comment]
Hai! Any updates on this feature?
