### ISSUE TITLE
Save draft of message when leaving the view.

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#388]
#### Description
When typing a message and then leave the chat screen the message is gone. It would be good to save it so that it is possible to continue after looking thing up in other apps or making a pause while writing.

#### To Reproduce
Go on a chat. Write a message. Do not sent the message. Go to the Main Page. Go back on the chat. Started message is gone. 

#### Additional information:
- Device: iPhone 12 mini
- OS and OS version: iOS 15.5
- Installed version of FluffyChat: 1.5.0
- (Android only) Which store are you using: 
- (Android only) Are Google Services available:

**Comment by Mikaela** [comment]
Duplicate of #3, but I should confirm whether this still happens.
