### ISSUE TITLE
Linux: graphical problems with tilling WMs and mobile

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#398]
Fluffychat seems to react poorly to being forced into a specific window geometry, flickering every time something might have to be redrawn (doens't flicker with static content and a stationary cursor)

Example with sway running on Manjaro, installed through flatpak , please excuse the hideous background

![Video Desktop](/uploads/d1e952f755f1e86da24eef7defb7a57c/stripped.mp4)

Example with Plasma Mobile, Pinephone, Manjaro ARM, also flatpak

![pinephone-fluffy](/uploads/bee2b227f2c74db5c7981545b40054c7/pinephone-fluffy.mp4)

**Comment by rasos** [comment]
Flickering is still a quite annoying issue, here on a Xubuntu Desktop via snap version rc1.21.2.

**Comment by meskio** [comment]
Still happening here using i3 on debian.
