### ISSUE TITLE
Autocompleting room results to ID instead of published alias when there is no canonical alias set

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#410]
#### Description

Conduit room has no canonical alias set, but has a published alias `#conduit:fachschaften.org`. When I type `#Cond` and select the correct room, I am instead given `!SMloEYlhCiqKwRLAgY:fachschaften.org` which cannot be used for joining the room.

#### To Reproduce

1. `/join #conduit:fachschaften.org`
2. Switch to another room
3. Start typing `#Conduit`
4. Select the room
5. See input bar having `!SMloEYlhCiqKwRLAgY:fachschaften.org` instead of `#conduit:fachschaften.org`

#### Additional information:
- Device: iPhone SE2020 A2296
- OS and OS version: iOS public beta 16.0 (20A538h) 
- Installed version of FluffyChat: 1.5.0 (22)
- (Android only) Which store are you using: Testflight

**Comment by Fabian42** [comment]
This is still an issue in 2.4.0 of the desktop version. No idea why the bot closes tickets where obviously nobody has worked on. Bugs don't just magically disappear over time.
