### ISSUE TITLE
Unable to paste iOS 16 & iPadOS 16

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#411]
#### Description
On iPhone or iPad copy text or image from safari. Go to FluffyChat and long press and or tap in input textbox, nothing happens. I would expect a popup dialog that asks me if I would like to copy / paste allowing me to paste the image / text. https://support.apple.com/guide/iphone/select-and-edit-text-iph1a9cae52c/ios

Tested with different texts / image strings and in multiple rooms. 

#### To Reproduce
Copy text, attempt to paste in FluffyChat in a group or in a chat. 

#### Additional information:
- Device: iPhone 12 Pro Max, iPad Air Gen 4
- OS and OS version: iOS 16
- Installed version of FluffyChat: 1.5.0

**Comment by MaximilianZenz** [comment]
I have the same problem.
