### ISSUE TITLE
Search Regression 1.6.x

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#430]
#### Description

In the new UI, it does not appear possible to search a different homeserver's room directory anymore.

It also seems no longer possible to simply *view* the directory, without a search term.

#### To Reproduce

* Be on a custom homeserver.
* Search for a public room, which would be in matrix.org's directory.
* No result.
* Try and find any option to search a different server's directory

#### Additional information:
- Device: 
- OS and OS version: 
- Installed version of FluffyChat: 
- (Android only) Which store are you using: 
- (Android only) Are Google Services available:

**Comment by Mikaela** [comment]
https://github.com/krille-chan/fluffychat/commit/62122e5c79eba103abcf48ce75fb560043ab64ee

**Comment by Mikaela** [comment]
no, I think this is actually a different issue, sorry.
