### ISSUE TITLE
Nested space functionality (Creation of space within space)

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#435]
#### Description
Hello Everyone,
There is app named "Element App", which developed using 'matrix-android-sdk2', there is a nested space functionality, So do this type of functionality exist in fluffychat app??
If yes, then how i can Integrate it? 
If not, then when will this type of functionality be integrated in fluffychat app?

#### To Reproduce
Here i attach screen shot of element app with nested space functionality.
![Screenshot_20220829-093459_Element](/uploads/231b7b7e91738988b06f249b87894160/Screenshot_20220829-093459_Element.jpg)

**Comment by wcjord** [comment]
Hey @krille-chan, are you saying that you'd like some help with this?

**Comment by krille-chan** [comment]
Not yet decided, how the GUI would fit into the design vision :-/

**Comment by krille-chan** [comment]
This is now partly implemented in an experimental manner

**Comment by wcjord** [comment]
@krille-chan Let me know if you'd like help with any improvements on this!
