### ISSUE TITLE
FluffyChat lags when there is many pinned messages

### ISSUE THREAD

**Issue by DarkCoder15** [krille-chan/fluffychat#463]
### Bug Description

If there is too many pinned messages in room, FluffyChat will be lagging. E.g. in a room bridged to telegram, which is a discussion group for a channel, every post will be pinned.

### Steps to Reproduce

1. Open any room with many pinned messages
2. FluffyChat will be lagging

### Expected Behavior

FluffyChat should not be lagging

### App Version

1.12.0

### Additional Platform Information

Android

**Comment by DarkCoder15** [comment]
dont see this issue in 1.14.0

**Comment by tux93** [comment]
> dont see this issue in 1.14.0

I don't know where you got 1.14, with 1.13 from F-Droid I still see the lagging behaviour

**Comment by krille-chan** [comment]
Should be fixed now :) from now on only the first pinned message is loaded (the one which is visible)
