### ISSUE TITLE
IOS app icon notification badge shows 1 even when everything is marked as read

### ISSUE THREAD

**Issue by ThatLurker** [krille-chan/fluffychat#469]
### Bug Description

The IOS app icon shows 1 notification even though everything is marked as read and no new notifications exist.
Sometime in a blue moon it can disappear for a while and the come back. 
![IMG_7912](https://github.com/krille-chan/fluffychat/assets/1533244/10b0c4b0-7b01-42fa-90e3-f76c128b7f2e)

### Steps to Reproduce

1. Get new message that causes the notification bubble to show up.
2. Mark everything as read.
3. See that the bubble is staying as 1

### Expected Behavior

When everything is read the bubble should not be there.

### App Version

1.12.0

### Additional Platform Information

iPhone 12 pro max

**Comment by krille-chan** [comment]
I hope the last commit has fixed it. I will push a new version to testflight soon

**Comment by mietzen** [comment]
I tested the latest TestFlight version but it’s still showing one unread message.

**Comment by pahakalle** [comment]
Yeah still shows every now and then, but now its not stuck at one unread always

**Comment by ThatLurker** [comment]
I'll close this as I have not seen the issue appear for a while now.

**Comment by sinnom** [comment]
I continue to have this problem on ios. It is stuck there always, even after reinstalling. When viewing a chat conversation, it additionally shows a little `1` badge on the button for returning to list of chats. Everything is read and there's no indication of what might be causing this badge to appear.

**Comment by klarlichter** [comment]
Hi. I also had that issue right now. It show always badge with „1“.
