### ISSUE TITLE
Fonts are too small on 4K display

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#47]
#### Description
On 4K displays fonts in Fluffychat window are too small, almost unreadable. Here are the screenshot of a Fluffychat window near the official desktop Element client:
![fonts](/uploads/3d2cda5b66057ba5fca2bde5b3adde12/fonts.png)

Please add the possibility to set up the font size.

#### To Reproduce
Run Fluffychat.

#### Additional information:
- Device: Lenovo Thinkpad P1 Gen 3
- OS and OS version: Ubuntu 20.10
- Installed version of FluffyChat: current Flathub version

**Comment by throwException** [comment]
I would very much appreciate any progress on this issue, as I'm a very near-sighted but enthusiastic user of fluffy.

I use:
* Device: Lenovo Thinkpad T15p
* OS and OS version: Debian 12 Bookworm
* Installed version of FluffyChat: current Flathub version
