### ISSUE TITLE
FIREFOX FLAGGED AS MALICIOUS

### ISSUE THREAD

**Issue by TheRealArchie** [krille-chan/fluffychat#471]
### Bug Description

![image](https://github.com/krille-chan/fluffychat/assets/80304455/73f1e430-77b2-4b87-9078-0def3556a5e9)

### Steps to Reproduce

Go on firefox and visite fluffychat.im 

### Expected Behavior

That this does not happen. 

### App Version

Browser

### Additional Platform Information

Desktop Firefox 115.0.2 (64-bit)

**Comment by krille-chan** [comment]
Thanks should be fixed now :) Please ping me if this happens again. Probably because the ssl cert has been renewed when migrating to github
