### ISSUE TITLE
Fluffychat.im showing 404

### ISSUE THREAD

**Issue by kojiinari** [krille-chan/fluffychat#475]
### Bug Description

https://fluffychat.im/ just goes to a 404 page
Error in multiple browsers: 
404

There isn't a GitHub Pages site here.

If you're trying to publish one, [read the full documentation](https://help.github.com/pages/) to learn how to set up GitHub Pages for your repository, organization, or user account.

Just thought someone would like to know.

### Steps to Reproduce

Go to https://fluffychat.im in any browser

### Expected Behavior

the site will load

### App Version

n/a

### Additional Platform Information

Any browser

**Comment by krille-chan** [comment]
Thanks, should be fixed now :)
