### ISSUE TITLE
Not really a feature rq but a suggestion.

### ISSUE THREAD

**Issue by rickdtc** [krille-chan/fluffychat#476]
### Feature Description

Well it would be better if the colors on these great parts were darker with matching material you

It would also be great if the tops were round too like the bottom

![Screenshot_20230727_222011](https://github.com/krille-chan/fluffychat/assets/74096544/1983d951-9ead-49eb-9b99-1dcd2659d3c3)
![Screenshot_20230727_221948](https://github.com/krille-chan/fluffychat/assets/74096544/080cc458-f782-4931-a058-26c0e066496c)

### Rationale

This would make the app  look better.

**Comment by krille-chan** [comment]
Hm, I think you are right. I will play around with the design a little bit. Thank you so much

**Comment by rickdtc** [comment]
Alright, no problem 👍

**Comment by rickdtc** [comment]
Goddamnit
