### ISSUE TITLE
Support knock_restricted join rule

### ISSUE THREAD

**Issue by aneverhopefulhelper** [krille-chan/fluffychat#480]
### Feature Description

Please could you add full support for knock_restricted as currently when trying to join a room with those join rules even if the user is in the rooms that should allows them through automatically they get a warning saying No permission, not even a knock is sent.

Thank you!

### Rationale

This feature should be supported because Spaces and rooms will implement this join rule and so do some already, therefore it is a necessity for users of Fluffychat.

**Comment by Mikaela** [comment]
I think join should just go through if you are in allowed rooms, but knocking is https://github.com/krille-chan/fluffychat/issues/152

**Comment by aneverhopefulhelper** [comment]
Seems you are correct, however in the settings "who can join" it still says "None" for both restricted and knock_restricted, not sure about just knock, so that should probably be changed too.

**Comment by Mikaela** [comment]
I think this is still the case, while my desktop FluffyChat is still /clearcacheing so I cannot check
