### ISSUE TITLE
Allow viewing full avatar.

### ISSUE THREAD

**Issue by CrimsonFork** [krille-chan/fluffychat#481]
### Feature Description

It would be nice to be able to view a full version of an avatar, both room and user.

### Rationale

There are more things that would be improved but the specific usability issue I have is that my profile picture is a rectangle, with some information hidden beyond the usually visible area, almost like a bit of a profile, however in FluffyChat there is no easily accessible way to see that.

(I even have a [project](https://codeberg.org/cf/pfpinator) to help take advantage of that.)

### Additional Context

This issue has been brought up in [#1127 on GitLab](https://gitlab.com/famedly/fluffychat/-/issues/1172) but wasn't imported here for some reason.

**Comment by DEFCON001** [comment]
This seems like a good idea to me too, my pfp is too
