### ISSUE TITLE
/markasdm does nothing

### ISSUE THREAD

**Issue by aneverhopefulhelper** [krille-chan/fluffychat#482]
### Bug Description

When attempting to convert a room into a DM with the /markasdm command it does not do so currently.

### Steps to Reproduce

1. Be in a room not currently marked as a DM.
2. Type /markasdm and press send/enter.

### Expected Behavior

The room gets converted to a DM.

### App Version

1.12.0

### Additional Platform Information

iPad OS 16.6

**Comment by krille-chan** [comment]
Thanks for the report. I have updated the translation string which explains the command. You have to add a matrix ID to make it work like: `/markasdm @someid:domain`

**Comment by aneverhopefulhelper** [comment]
Thank you, I have tried out the method you described here in 1.12.0 and confirmed it works :slightly_smiling_face:
