### ISSUE TITLE
Code Blocks show only on one line

### ISSUE THREAD

**Issue by aneverhopefulhelper** [krille-chan/fluffychat#483]
### Bug Description

On Flufychat when trying to view a code block currently they only display as one line which makes it very difficult to view the content of them as it means having to scroll horizontally.

### Steps to Reproduce

1. Make a code block with content on multiple lines or call one from a bot.

### Expected Behavior

Have the content of the code block appear on multiple lines.

### App Version

1.12.0

### Additional Platform Information

iPad OS 16.6

**Comment by krille-chan** [comment]
![Screenshot_20230730-105152_1.png](https://github.com/krille-chan/fluffychat/assets/24619905/07edd638-8f96-469f-839f-28b6809ee71f)

Hm I am not sure that I understand what you mean. When I post a vode block it is displayed multiline without a problem for me...

**Comment by aneverhopefulhelper** [comment]
![TOML](https://github.com/krille-chan/fluffychat/assets/91751074/5baedb85-2ca4-4f81-a1fb-50cf2a68ad33)
![TOMLR](https://github.com/krille-chan/fluffychat/assets/91751074/024a9ca4-234c-4183-b1ba-9ffc75286ae3)
![MHOMLR](https://github.com/krille-chan/fluffychat/assets/91751074/11e10803-f90d-45b5-96a6-6df06e7a7965)


This is what I mean.

**Comment by aneverhopefulhelper** [comment]
Fixed in 1.13.0 for me on iPad OS 16.6

**Comment by osnyx** [comment]
I can confirm this for Android as well, 1.13.0 has resolved this issue.

**Comment by schmittlauch** [comment]
This issue can be considered as resolved.
