### ISSUE TITLE
Going back while viewing the contents of a space brings you back to wrong page

### ISSUE THREAD

**Issue by KSPAtlas** [krille-chan/fluffychat#484]
### Bug Description

Using the android back button, if you attempt to go back from viewing the contents of a space you are in (the view with the list of rooms), you are taken back to the rooms list, not the correct spaces list.

### Steps to Reproduce

1. Use Fluffychat on an Android device
2. Join a space
3. Open the space view and view the rooms of the space you joined
4. Attempt to go back using the back button
5. Observe bug

### Expected Behavior

The back button would instead take me back to the spaces list, as that was the one i was in previously

### App Version

1.12.0

### Additional Platform Information

Android 13 on Google Pixel 6, Stock ROM

### Additional Context

I was using gesture navigation when testing this bug

**Comment by DarkCoder15** [comment]
same on 1.13.0
