### ISSUE TITLE
Crash when trying to login to homeserver that does not return `identity_providers` field of `m.login.sso` flow schema

### ISSUE THREAD

**Issue by hughns** [krille-chan/fluffychat#489]
### Bug Description

FluffyChat is unable to sign in to a Matrix homeserver that offers the `m.login.sso` login type but where the homeserver does not provide a list of identity providers.

Instead the user ends up stuck on a greyed overlay screen with an error visible in the Javascript console.

### Steps to Reproduce

1. Go to https://fluffychat.im/web
2. Enter homeserver `synapse-oidc.lab.element.dev` into search box
3. Press enter/return key
4. You end up on a greyed out screen
5. Check the Javascript console and see the following error:

```
TypeError: null: type 'minified:Op' is not a subtype of type 'List<dynamic>'
js_primitives.dart:42     at Object.j (https://fluffychat.im/web/main.dart.js:5207:3)
js_primitives.dart:42     at Object.cuj (https://fluffychat.im/web/main.dart.js:5910:18)
js_primitives.dart:42     at ru.cYX [as a] (https://fluffychat.im/web/main.dart.js:5905:3)
js_primitives.dart:42     at Zl.gbBz (https://fluffychat.im/web/main.dart.js:94932:17)
js_primitives.dart:42     at amK.B (https://fluffychat.im/web/main.dart.js:95045:30)
js_primitives.dart:42     at Rg.ez (https://fluffychat.im/web/main.dart.js:139157:32)
js_primitives.dart:42     at Rg.zW (https://fluffychat.im/web/main.dart.js:139135:9)
js_primitives.dart:42     at Rg.a9e (https://fluffychat.im/web/main.dart.js:139105:10)
js_primitives.dart:42     at Rg.eH (https://fluffychat.im/web/main.dart.js:139159:6)
js_primitives.dart:42     at lB.qV (https://fluffychat.im/web/main.dart.js:138975:3)
```

### Expected Behavior

In the case that the homeserver does not specify a list of identity providers it should show a single SSO login button labelled something similar to "Continue with SSO".

### App Version

1.13.0

### Additional Platform Information

Chrome 115.0.5790.114

### Additional Context

The response to `GET https://synapse-oidc.lab.element.dev/_matrix/client/v3/login` is:

```json
{
    "flows": [
        {
            "type": "m.login.password"
        },
        {
            "type": "m.login.sso",
            "org.matrix.msc3824.delegated_oidc_compatibility": true
        },
        {
            "type": "m.login.token"
        }
    ]
}
```

Which is valid as per the `m.login.sso flow schema` section of https://spec.matrix.org/v1.7/client-server-api/#client-login-via-sso because the `identity_providers` field is optional:

> Optional identity providers (IdPs) to present to the user. These would appear (typically) as distinct buttons for the user to interact with, and would map to the appropriate IdP-dependent redirect endpoint for that IdP.

**Comment by raku-cat** [comment]
Came here after running in to the same thing on Android.  Do you know if adding an OIDC provider the standard way in addition to the MAS would work as a temporary shim? Going to test this myself eventually but just curious if you've already tried.

**Comment by krille-chan** [comment]
Thanks for reporting. This should be fixed with the latest commit. You should be able to try it out by yourself on the web platform in a few minutes
