### ISSUE TITLE
Message status indicators

### ISSUE THREAD

**Issue by K4LCIFER** [krille-chan/fluffychat#501]
### Feature Description

It's very helpful to have little indicators for the current status of the message, i.e. Read, Sent, Delivered, etc. I propose that these indicators get tacked on to the messages to tell you its status. 

### Rationale

Its very useful to know the current status of a message.

### Mockup

The most common functionality is 3 states: "Sent", "Delivered", and "Read". each one of thes should have an icon that appears beside the message to indicate what state it is in.

**Comment by sunjam** [comment]
open
