### ISSUE TITLE
The emoji picker does not follow the theme

### ISSUE THREAD

**Issue by K4LCIFER** [krille-chan/fluffychat#504]
### Bug Description

As shown in the following picture, the emoji picker does not follow the set theme

![Screenshot_20230806-141928](https://github.com/krille-chan/fluffychat/assets/7829231/32bf3ad8-3d13-463b-8973-8f03e6f34c05)

### Steps to Reproduce

1. set the theme to dark mode
2. open the emoji picker
3. observe that it doesn't follow the theme choice, and stays in light mode

### Expected Behavior

I'd expect that it would follow the theme setting

### App Version

1.13.0

### Additional Platform Information

Google Pixel 6, Android 14 beta

**Comment by reinhart1010** [comment]
This is because FluffyChat uses components from [emoji_picker_flutter version 1.5.1](https://pub.dev/packages/emoji_picker_flutter), and older versions of it doesn't allow fine-tuning of the keyboard's accent color (resolved as of version 1.6.1). Might create a to fix that.
