### ISSUE TITLE
FluffyChat does not launch on Linux anymore

### ISSUE THREAD

**Issue by lfom** [krille-chan/fluffychat#506]
### Bug Description

Hello!

Just a heads up: I did a quick search but did not find anything related, so I thought it would be a good idea to register it. since v1.13.0-1 the Linux binary does not launch anymore, it complains about a missing library:
```
fluffychat: error while loading shared libraries: libwebrtc.so: cannot open shared object file: No such file or directory
```
The library is included in the lib folder, so this works:
```
LD_LIBRARY_PATH=./lib ./fluffychat
```

### Steps to Reproduce

1. Download the Linux tarball
2. Extract and try to lunch FluffyChat
3. App does not launch, complains about missing library

### Expected Behavior

App should lunch (previous versions from Gitlab did btw).

### App Version

1.13.0

### Additional Platform Information

Arch Linux

### Additional Context

So the package _fluffychat-bin_ (and probably _fluffychat_ too), as well as the binaries from chaotic-aur do not work either.

**Comment by krille-chan** [comment]
Absolutely no idea >.< I have tried to set this env variable in the snap version but no luck...

**Comment by xangelix** [comment]
Appears to be fixed for me in https://github.com/krille-chan/fluffychat/releases/tag/v1.14.0
is this the same case with you @lfom ?

**Comment by lfom** [comment]
Yes, v1.14.0 works out the box now, not more error about missing libraries.

Thanks!
