### ISSUE TITLE
Forwarded messages from mautrix-telegram does not render

### ISSUE THREAD

**Issue by q234rty** [krille-chan/fluffychat#507]
### Bug Description

Forwarded messages on the telegram side bridged by mautrix-telegram does not render.

### Steps to Reproduce

1. Send `<tg-forward><blockquote>message</blockquote></tg-forward>` in element desktop with /html

2. Observe that message does not render.

### Expected Behavior

message is rendered fine.

### App Version

rc1.13.0-2

### Additional Platform Information

Arch Linux

### Additional Context

I _think_ this is a regression from https://github.com/krille-chan/fluffychat/commit/796a6fdae181eb1118bffdb05f2e6e3d378fe6c4

**Comment by krille-chan** [comment]
Can you please test this with the newest main version? I've added it to the allowed tags

**Comment by q234rty** [comment]
I tried compiling from git but it still doesn't work for some reason

**Comment by jahway603** [comment]
I'm running the latest version on F-Droid, Version 1.16.0 (3523), Added on 2023-12-10, and this issue is still happening.

**Comment by krille-chan** [comment]
Fixed in latest commit
