### ISSUE TITLE
multi-account beta: Changing device orientation resets view to main account

### ISSUE THREAD

**Issue by schmittlauch** [krille-chan/fluffychat#511]
### Bug Description

When using multiple accounts in Fluffychat 1.12, rotating the device exits the current chat room and resets the view to the room overview of the primary account. With *primary matrix account* I mean the first account added to Fluffychat.

This is the case for both rooms of the primary account and rooms of additional accounts, but the reset alway goes back to the overview of the primary account.

### Steps to Reproduce

1. add multiple accounts to FluffyChat by enabling the multi-account beta
2. enter the view for a chat room from the account you added first
3. rotate your device such that the app orientation changes
4. observation: the view is reset to the overview of the primary account
5. in the overview, click your avatar and chose one of the non-primary accounts
6. enter the view for a chatroom
7. rotate your device such that the app orientation changes
8. observation: the view is reset to the overview of the primary account

### Expected Behavior

Changing the app display orientation shall only change the layout of the view, but keep the current room of the currently enabled account.

### App Version

1.12.0

### Additional Platform Information

Devices: FxTec Pro1 (LineageOS 20 = Android 13), Sony Xperia 10 III with SailfishOS (Android App Support, API level Android 11)

**Comment by krille-chan** [comment]
Should be fixed in newest version :-) I maybe was able to fix this state management bug

**Comment by schmittlauch** [comment]
F-Droid just released the 1.13 build, this indeed has fixed this issue for me. Thanks a lot.
