### ISSUE TITLE
Allow changing message size

### ISSUE THREAD

**Issue by Heus-Sueh** [krille-chan/fluffychat#517]
### Feature Description

Allow to change the size of the message, on my cell phone I think the font is a little too big

### Rationale

because it would help with the issue of accessibility, for example

### Mockup

Like Telegram:
![Screenshot_20230814-112702_Telegram-cropped](https://github.com/krille-chan/fluffychat/assets/98482469/0bd59ac2-3cd1-41e1-9bde-6b0098671396)

**Comment by krille-chan** [comment]
Already implemented. Go to settings > Style >

**Comment by Heus-Sueh** [comment]
> Already implemented. Go to settings > Style >

sorry, it's just that I just found out that the latest version of the app always arrives later on f-droid
