### ISSUE TITLE
First stories appear to be unencrypted

### ISSUE THREAD

**Issue by spiralhalo** [krille-chan/fluffychat#520]
### Bug Description

The first story ever posted by an account appear to be unencrypted. This is a cause of concern for privacy.

Second and further stories seem encrypted as expected, as seen from Element.

I tested this on two accounts, see attached screenshots below.

![2023-08-17 08_17_44-Element Stories from spiralhalo](https://github.com/krille-chan/fluffychat/assets/8444172/5a75bf24-c115-4e7e-a751-4d6cd583643e)

![2023-08-17 08_18_31-Element Stories from spiralhalo alt — Mozilla Firefox](https://github.com/krille-chan/fluffychat/assets/8444172/4d03c0d0-4617-420d-8f43-f4421869e4a5)

### Steps to Reproduce

Make a story with an account that had never made stories before

### Expected Behavior

All stories are encrypted

### App Version

1.13.0

### Additional Platform Information

Android 10

**Comment by krille-chan** [comment]
Thanks, I think I found the cause. Looks like the server is not sending the state events correctly in the first sync after creating the rooms or maybe the matrix dart sdk is not waiting for the sync to be processed before returning `waitForRoomInSync()`. I will open upstream issues

**Comment by krille-chan** [comment]
I have pushed a workaround in main branch. New stories are now always encrypted

**Comment by vehosah** [comment]
By the way how you created stories?

**Comment by Mikaela** [comment]
The feature is removed in favour of status.
