### ISSUE TITLE
The jitsi matrix widget cannot be used on linux desktop

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [krille-chan/fluffychat#521]
### Bug Description

I'm using the fluffychat from flathub and really like its design and simplicity some things are not working correctly so I wanted to create bug reports for them. If they are not in the correct spot or specific to the flatpak, let me know so that they can be placed at the correct spot.

As the title says, there is a problem with the matrix flathub widget. It is listed in the list of widgets, but after clicking on it, nothing happens. I expected, that it works like in element, that a side bar or top window opens with the integrated element chat, but nothing happens. On the android client, the jitsi session can be opened in an browser or element. This is suboptimal as it is not integrated into the app, but a workable workaround for mobile. On the desktop though, this does not work.

### Steps to Reproduce

1. Open a chat, that has an jitsi matrix widget already added to it. I did this with element.
2. Click on the 3-Point-Button in the right corner.
3. Choose the entry "Matrix-Widgets".
4. In the now open bottom drawer, click on the jitsi entry.

### Expected Behavior

The jitsi session should be opened inside fluffychat so that it is possible to have a video conference or voice chat inside fluffychat.

### App Version

1.12.0

### Additional Platform Information

Device: PC, OS: Fedora Linux 38

### Additional Context

The package used for testing was the one from flathub, which currently sits on version 1.12.

**Comment by krille-chan** [comment]
Thanks. Widgets have been removed in the upcoming version so I will close this issue

**Comment by Sebastian-Hirsch** [comment]
That is kind of a shame as now there are no options for voice- and videochat anymore. Is there anything planned? I saw a beta feature in element with there own implementation of voip rooms:

![grafik](https://github.com/krille-chan/fluffychat/assets/41188546/0c3e71c6-eb16-44da-985b-3b0768718012)

**Comment by alexander-potemkin** [comment]
FYI, Element's call still can't be enabled on a self-hosted instance and require quite specific Matrix server configuration, f.ex.: registration enabled for everybody.
