### ISSUE TITLE
Retrieving the logs does not work in the linux client when using the flatpak

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [krille-chan/fluffychat#523]
### Bug Description

With the current version on flathub, I cannot retrieve the logs for fluffychat from inside the about dialog. When clicking on the logs button, nothing happens.

### Steps to Reproduce

1. Click on the avatar inside the search field.
2. Click on "Settings".
3. In the left sidebar, click on "About".
4. Click on the "Logs" button.

### Expected Behavior

After clicking the "Logs" button, the logs should either be shown inside the app or the folder that contains them should be opened in the file manager.

### App Version

1.12.0

### Additional Platform Information

Device: PC, OS: Fedora Linux 38

### Additional Context

The package used for testing was the one from flathub, which currently sits on version 1.12.

**Comment by krille-chan** [comment]
thanks. Will be fixed in the next version

**Comment by Sebastian-Hirsch** [comment]
Nice, thanks for the fix!
