### ISSUE TITLE
Cannot login - Upload key failed

### ISSUE THREAD

**Issue by Zelaf** [krille-chan/fluffychat#529]
### Bug Description

I wanted to give FluffyChat a go and downloaded it on my phone, when I pressed login it booted me back to the "Let's start" menu. I tried on my linux computer as well and got the same error so I opened the console and I got an error regarding uploading the key.

### Steps to Reproduce

1. Launch FluffyChat
2. Click on login
3. Login with password

### Expected Behavior

Actually logs in.

### App Version

1.12.0

### Additional Platform Information

Device: Laptop, Fairphone 4 OS: Manjaro, Android 12

### Additional Context

The error in the log is:
```
flutter: [Matrix] Initialization failed - Upload key failed
#0      OlmManager.init (package:matrix/encryption/olm_manager.dart:75)
<asynchronous suspension>
#1      Encryption.init (package:matrix/encryption/encryption.dart:76)
<asynchronous suspension>
#2      Client.init (package:matrix/src/client.dart:1482)
<asynchronous suspension>
#3      Client.login (package:matrix/src/client.dart:542)
<asynchronous suspension>
#4      LoginController.login (package:fluffychat/pages/login/login.dart:70)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Upload key failed
#0      OlmManager.init (package:matrix/encryption/olm_manager.dart:75)
<asynchronous suspension>
#1      Encryption.init (package:matrix/encryption/encryption.dart:76)
<asynchronous suspension>
#2      Client.init (package:matrix/src/client.dart:1482)
<asynchronous suspension>
#3      Client.login (package:matrix/src/client.dart:542)
<asynchronous suspension>
#4      LoginController.login (package:fluffychat/pages/login/login.dart:70)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Upload key failed
#0      OlmManager.init (package:matrix/encryption/olm_manager.dart:75)
<asynchronous suspension>
#1      Encryption.init (package:matrix/encryption/encryption.dart:76)
<asynchronous suspension>
#2      Client.init (package:matrix/src/client.dart:1482)
<asynchronous suspension>
#3      Client.login (package:matrix/src/client.dart:542)
<asynchronous suspension>
#4      LoginController.login (package:fluffychat/pages/login/login.dart:70)
<asynchronous suspension>
```

I'm guessing it has to do with my over-complicated generated password. It's very long and has a lot of special characters. It's not the first time I've tried using something where that has been a factor.

**Comment by krille-chan** [comment]
Looks like the device is unable to upload the olm keys after a successful login. Maybe your server is not spec conform? When the "login" fails at the upload key stage then your password already worked so that is not the problem here. However for everyone else it seems to work.

**Comment by Zelaf** [comment]
I use the matrix.org server for my account so hardly think it's the server. I saw some other people have been having password related issues too when I posted to Matrix about it. Since it happens to two devices it must be something with either the account or my password.

I could change it to a simpler password to test but a part of me really don't want to do that but I'll see if I get the time to do that later today.

**Comment by Zelaf** [comment]
Alright, update, tried to switch to a more basic password and it worked. Must be something of the characters of the generated passwords. Either it was the length (32 characters) or it was the special characters (`!@#$%^&*`). I'll try some more tests.
