### ISSUE TITLE
Donate, AuthorWebSite on fdroid metadata

### ISSUE THREAD

**Issue by ghost** [krille-chan/fluffychat#534]
### Feature Description

@krille-chan 
* **without your explicit consent** Donate ```https://ko-fi.com/krille``` & Liberapay ```KrilleChritzelius``` from https://github.com/krille-chan/fluffychat#links AND 
AuthorWebSite ```https://krille-chan.github.io``` from https://github.com/krille-chan was updated by me in [fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/chat.fluffy.fluffychat.yml)
* fdroid [policy](https://gitlab.com/fdroid/admin/-/issues/417) and [suggestion](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13549#note_1508711371) wrt to adding AuthorEmail, AuthorWebSite, Donate, etc..
* should i remove it?

### Rationale

Na

**Comment by krille-chan** [comment]
Thanks, that's fine for me. I will soon try to update all f-droid metadata and take a look on it.
