### ISSUE TITLE
Not working on Android 4.4

### ISSUE THREAD

**Issue by quantumde1** [krille-chan/fluffychat#535]
### Bug Description

When installing APK and trying to launch, splash of app with logo is appeared, and after second app is exiting with an error.

### Steps to Reproduce

1. Try to install latest fluffychat apk to Android 4.4 on Galaxy GT-i9192 with Cyanogenmod

### Expected Behavior

App will run, but it didn't.

### App Version

1.13.0

### Additional Platform Information

Samsung Galaxy S4 Mini Duos GT-i9192 with CyanogenMod

**Comment by warren-bank** [comment]
fwiw, the [Flutter docs](https://docs.flutter.dev/reference/supported-platforms) say:
* Android 5.0 (Lollipop, API 21) and higher is fully supported
* Android 4.4 (KitKat, API 19-20) is a "best effort"..<br>not all features are guaranteed to work
