### ISSUE TITLE
Use better default name than "Empty Chat" on groups with no name

### ISSUE THREAD

**Issue by ownbee** [krille-chan/fluffychat#542]
### Feature Description

Rooms with no name get the name "Empty Chat" which is uninformative and messy if you have multiple.

Would be much better to either:

1. Default to "Name1, Name2 and 3 others".
2. Or be able so set an own alias locally in the app.

### Rationale

I am using mautrix-facebook to sync Facebook chats which create groups that you cannot change name on (makes sense since it syncs the Facebook name). However, I have multiple Facebook group chats without name. This works good in Facebook since Facebook automatically sets the name to participant list, e.g.: "Firstname1, FirstName2 and FirstName3". 

It is the same case with nheko Linux desktop client, there it names no-name groups "name1 and X others".  This isn't ideal though since "name" is the full name which contains too many characters to contain more than one or two participants.

This could be fixed in mautrix-facebook as well but I think "Empty Chat" is not a good default name...

**Comment by ToasterUwU** [comment]
I just encountered this.

Its so confusing, I have to guess based on the icons shows which channel it is because I have 3 different "Empty Chats"

**Comment by ToasterUwU** [comment]
Also, stale bots that close issues are horrible. Please don't do that, all it does is brush real problems under the rug while pretending they are fixed.

Mark them as stale sure, but don't close an issue because no-one keep spaming "Not stale" every few days
