### ISSUE TITLE
MSC4030: JPEG XL support

### ISSUE THREAD

**Issue by avidseeker** [krille-chan/fluffychat#547]
### Feature Description

The app can't preview JPEG XL (.jxl) files. It would be great if JPEG XL support was added. [jxl viewer](https://github.com/oupson/jxlviewer) for Android might be helpful.

### Rationale

Matrix Spec proposal: https://github.com/ru-ka/matrix-spec-proposals/blob/main/proposals/MSC4030%3A%20Progressive%20images%20in%20Matrix.md

**Comment by Mikaela** [comment]
Upstream practically delegates this to the device.

- https://github.com/flutter/flutter/issues/113476#issuecomment-1306077546
