### ISSUE TITLE
Easier copying of the matrix handle / alias / user address / identifier to clipboard

### ISSUE THREAD

**Issue by ZenKyma** [krille-chan/fluffychat#552]
### Feature Description

It would be nice to have an easy way to copy the matrix alias (e.g. @timofej:matrix.org) to clipboard from the contact details interface in a chat, either via a dedicated button or by long-pressing on the displayed matrix alias (the latter being the expected behaviour).

### Rationale

Simplifying the retrieval of the contact id down to two clicks, especially in the light of having to use the `/markasdm @name:server.domain` command frequently for fixing DM chats.

### Mockup

![Screenshot_20230902-020915](https://github.com/krille-chan/fluffychat/assets/116916092/87eae8b5-808d-416c-b3e6-95550dad099e)
Possible realisation as a button.

### Additional Context

Currently it feels cumbersome to retrieve the id, three clicks are needed to go to export contact and copy the plaintext from there, plus two actions to close down the open interfaces again.

**Comment by Mikaela** [comment]
Unable to reproduce on current Testflight
