### ISSUE TITLE
[iOS] Can’t send screenshot directly

### ISSUE THREAD

**Issue by marekjedrzejewski** [krille-chan/fluffychat#559]
### Bug Description

When screenshot is captured there’s its thumbnail that user can click and do quick actions. When share to FluffyChat is clicked, screen just blinks and nothing happens

### Steps to Reproduce

1. Capture screenshot
2. Click thumbnail
3. Click share
4. Select FluffyChat
5. 😿

### Expected Behavior

We should be able to send screenshot without saving it first

### App Version

1.13.0

### Additional Platform Information

iPhone 12 mini

**Comment by reinhart1010** [comment]
This might be related to #203.

**Comment by antdude** [comment]
I have this problem too in my iPhones 12 mini. :(
