### ISSUE TITLE
Multi-account login with password is broken and returns to the first account

### ISSUE THREAD

**Issue by Mikaela** [krille-chan/fluffychat#569]
### Bug Description

When attempting to login by password as additional account, you are thrown back to the account you were using previously.

### Steps to Reproduce

1. Open FluffyChat
2. Touch your avatar
3. Select add account
4. Confirm the beta prompt
5. `matrix.org` is pre-filled, select login by password.
6. You are returned to step 1. without errors or indication what went wrong.

### Expected Behavior

I expected to get the prompt asking for my username and password after which the login flow should have continued as usual.

### App Version

1.14.0 (59), 1.14.0

### Additional Platform Information

iPhone SE2020, OUKITEL K15 Pro

### Additional Context

I first thought this was specific to `beeper.com` homeserver, but then thought to try `matrix.org` and noticed that it seems to be independent of the homeserver.

**Comment by krille-chan** [comment]
Fixed with latest commit :)
