### ISSUE TITLE
Inconsistent font sizes when OS has non-default font size (HTML messages are bigger)

### ISSUE THREAD

**Issue by gabrc52** [krille-chan/fluffychat#577]
### Bug Description

Some messages seem to have a large font size for some reason:

![image](https://github.com/krille-chan/fluffychat/assets/24363938/930a7ddf-937f-4cd9-beac-e7e46c010326)

![image](https://github.com/krille-chan/fluffychat/assets/24363938/7d018a13-1d50-4088-a64f-eacc418db811)

It seems like HTML-containing messages have a bigger font than plaintext-only messages

### Steps to Reproduce

Change the system font

![Screenshot_20231029-205938](https://github.com/krille-chan/fluffychat/assets/24363938/f0335399-70c7-4a76-847a-20946b942a62)

Send messages in a room, alternating between HTML-containing and plaintext-only messages.

### Expected Behavior

Text has a consistent size

### App Version

1.14.0

### Additional Platform Information

Android 13 on Pixel 6

**Comment by gabrc52** [comment]
I've realized something else. This only happens when you change the font size in system settings from the default. If you go back to the default size the messages have consistent sizes.

**Comment by seankhl** [comment]
Just wanted to chime in that this is affecting me and is a pretty big issue for usability and the overall appearance of the app IMO.

related/duplicates: https://github.com/krille-chan/fluffychat/issues/537, https://github.com/krille-chan/fluffychat/issues/488

**Comment by gabrc52** [comment]
I am looking into this and have found the source of this bug to be in the `flutter_linkify` library: https://github.com/Cretezy/flutter_linkify/issues/135

The last time someone brought it up, the developer of the library blamed Flutter: https://github.com/Cretezy/flutter_linkify/issues/22

I will work on a PR to the upstream library.
