### ISSUE TITLE
Select menus are unthemed

### ISSUE THREAD

**Issue by gabrc52** [krille-chan/fluffychat#578]
### Bug Description

Select menus are unthemed:

![image](https://github.com/krille-chan/fluffychat/assets/24363938/987954e6-be74-454e-bdcb-a1dabc556e67)

### Steps to Reproduce

1. Change to dark theme
1. Go to a room
2. Click on the name/profile icon
3. Click on "Who is allowed to join this group"

### Expected Behavior

The menu respects the theme

### App Version

1.14.0

### Additional Platform Information

Android 13 on Pixel 6

**Comment by reinhart1010** [comment]
Good catch. Also reproducible in iOS.

![image](https://github.com/krille-chan/fluffychat/assets/17312341/faa51b55-8212-472e-868b-847a93b85a3b)
![image](https://github.com/krille-chan/fluffychat/assets/17312341/f59bfc1f-a331-4896-a171-16d71ac4c7e6)

**Comment by reinhart1010** [comment]
Anyway @krille-chan it looks like `knock` and `private` are untranslated properly. Aren't they supposed to be `anyoneCanKnock` and `noOneCanJoin` just like https://github.com/krille-chan/fluffychat/blob/40f6fe17bebc9f7afe82332a5c763d07b772ce3e/assets/l10n/intl_en.arb#L1045 ?

**Comment by gabrc52** [comment]
Seems resolved
