### ISSUE TITLE
Incorrect configuration behavior of privacy_url in config.json for the web app

### ISSUE THREAD

**Issue by dlyrsk** [krille-chan/fluffychat#581]
### Bug Description

The `privacy_url` configuration in `config.json` for the web app doesn't work. 

### Steps to Reproduce

1. Create a `config.json` that contains the `privacy_url` configuration for the web app:
```json
{
    "privacy_url": "https://github.com/krille-chan/fluffychat/blob/main/README.md"
}
```
2. In the web app, open `Settings -> Privacy`

### Expected Behavior

The `privacy_url` configuration will work in the web app, as well as the `web_base_url` configuration.

### App Version

1.14.1

### Additional Platform Information

Chrome Version 117.0.5938.89

### Additional Context

It seems the configuration value is assigned to wrong variables:
https://github.com/krille-chan/fluffychat/blob/2713b38b80af3287bfc9ce94af59a59aa06f2fdf/lib/config/app_config.dart#L93-L98

**Comment by biowilli** [comment]
I had the same issue, fix it with:

```
if (json['privacy_url'] is String) {
  _privacyUrl = json['privacy_url'];
}
if (json['web_base_url'] is String) {
  _webBaseUrl = json['web_base_url'];
}
```
