### ISSUE TITLE
Optional Link Embeds

### ISSUE THREAD

**Issue by mindmeshlink** [krille-chan/fluffychat#583]
### Feature Description

I would like an option (Embed links in chat) or perhaps a pair of them (One for unencrypted chats, one for encrypted ones), which causes links in fluffychat to display an embed containing images and text for a given link with appropriate Open Graph meta tags.

### Rationale

I have a close friend who frequently sends me a lot of links. Especially on Android, this means to know anything beyond a URL, I have to click the link, click into a menu to open the link, then wait for my browser to load, switch back to the app, and repeat.

I recognize that Element has been opinionated about this due to security concerns - generating embeds does fetch from servers. That's real, and why I'm suggesting it be an option. I could even see it as per-room if we want to be storing that kind of state. Personally, that issue is outside of my threat model, so I'd like the option at least.

### Mockup

I haven't made any mockups, but I can come back and edit some in later if desired.

**Comment by viscountexx** [comment]
I didn't check my email, but I still want this feature. Please un-stale it.

**Comment by Henry-Hiles** [comment]
I agree, this would be great
