### ISSUE TITLE
[Feature Request] Custom Emoji fonts

### ISSUE THREAD

**Issue by MuhannadYT** [krille-chan/fluffychat#585]
### Feature Description

The ability to change emoji's font in the App using a tff/otf file.

### Rationale

This feature will allow people to override the default emojis on their devices, this gives the ability for users to pick the emoji style that they prefer

**Comment by krille-chan** [comment]
Sorry this does not fit into the design vision :-/ We don't plan to implement so many config features to be able to focus more on stability

**Comment by Mikaela** [comment]
Related: #188
