### ISSUE TITLE
Ogg files not played

### ISSUE THREAD

**Issue by scmanjarrez** [krille-chan/fluffychat#587]
### Bug Description

Audio messages in ogg format aren't played in desktop client (flatpak), instead you have to download them and play in a separate app.

### Steps to Reproduce

1. Receive ogg file
2. Only download button is shown

### Expected Behavior

Be able to play audio messages in ogg format.

### App Version

1.14.1

### Additional Platform Information

flatpak

### Additional Context

![image](https://github.com/krille-chan/fluffychat/assets/9284124/24823d7a-0642-40a1-8927-ae509d9650ee)

**Comment by PgBiel** [comment]
I can still reproduce this issue.
