### ISSUE TITLE
Paste image from clipboard

### ISSUE THREAD

**Issue by scmanjarrez** [krille-chan/fluffychat#589]
### Bug Description

Images from clipboard aren't pasted.

### Steps to Reproduce

1. Copy image to clipboard
2. Paste in chat
3. Nothing happens

### Expected Behavior

Image is pasted so you can send it

### App Version

1.14.1

### Additional Platform Information

flatpak

### Additional Context
This feature was implemented in https://github.com/krille-chan/fluffychat/pull/461/commits/2ae4551bcc91a47cef9d31630ab0065cf59d29dc, so I don't know if it's a bug or a limitation related to flatpak package

**Comment by Mikaela** [comment]
I am able to reproduce this on `sway version 1.8.1`, but someone at the Matrix room cannot, so I wonder if this is perhaps related to wayland? I was attempting to copy an image from Telegram to test this issue and both apps are running under `xdg_shell` so native wayland.

What display or window manager are you using and is it wayland?

**Comment by scmanjarrez** [comment]
Hi, thanks for your response. I'm using Xfwm4 as window manager and Xfce as desktop environment. I don't have any problem using telegram (but I'm using binary, not flakpak)

**Comment by florianschroen** [comment]
same here (can not paste images to chat)

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Linuxmint
Description:    Linux Mint 21
Release:        21
Codename:       vanessa

$ dpkg -l | grep xorg
ii  xorg                                           1:7.7+23ubuntu2                            amd64        X.Org X Window System

$ xset q >/dev/null && echo Xorg is running
Xorg is running

$ flatpak list | grep fluffy
Fluffychat      im.fluffychat.Fluffychat        1.14.1  stable  system
```

**Comment by sybrenstuvel** [comment]
This is still an issue with FluffyChat 2.1.1 on macOS 26.0.1 (25A362). I would argue this is expected functionality for any chat client that can send images.
