### ISSUE TITLE
[Feature Request] Auto download images

### ISSUE THREAD

**Issue by MuhannadYT** [krille-chan/fluffychat#590]
### Feature Description

In many apps (singal, whatsapp, telegram) when you receive a picture it is stored on the device as well. This feature would allow the user to select specific groups that it would auto download from. Also, the ability to have it store them in the DCIM would be great as well.

A good alternative is having an option to change where downloaded media is stored 

### Rationale

It is beneficial when your family or friends send you a picture, it goes into the gallery (or at least the option).  Makes it a more seamless experience for family and friends to start using the matrix protocol

**Comment by Terkyz** [comment]
This was never implemented, or I'm wrong?

If not, please open the issue again, I'm honestly also interested in this.
