### ISSUE TITLE
Desktop: Allow selecting and copying text

### ISSUE THREAD

**Issue by throwException** [krille-chan/fluffychat#598]
### Feature Description

In the desktop app I would like to select text in chat messages and copy the by Ctrl+C and/or right click menu as in other desktop apps.

### Rationale

I use Matrix often to send and receive text snippets.

**Comment by Janavanwalde** [comment]
Hi, it's not yet decided how this should be solved. :)

**Comment by Janavanwalde** [comment]
Hey, the function has been installed and will be available in the next release,

**Comment by throwException** [comment]
> Hey, the function has been installed and will be available in the next release,

Thanks, very much appriciated!
