### ISSUE TITLE
Chat Backup issue

### ISSUE THREAD

**Issue by codingnooob** [krille-chan/fluffychat#601]
### Bug Description

When I try to enable chat backup on the iOS app, it just says “Oops, something went wrong…”

### Steps to Reproduce

1. Go to Account/Settings
2. Tap on “Chat Backup”
3. Select “Store in Apple Keychain” and/or “Copy to Clipboard” (error occurs either way)
4. Error message (“Oops, something went wrong…”)

### Expected Behavior

The backup goes through without errors

### App Version

1.14.3

### Additional Platform Information

iPhone SE 2 (iOS)

### Additional Context

![IMG_5013](https://github.com/krille-chan/fluffychat/assets/66186626/bfec6d01-e572-483f-8a62-99f8c3fe5473)

**Comment by Janavanwalde** [comment]
Hi, unfortunately I can't reproduce this, but we'll do it this way. In the next version, if the error occurs again, we'll add an error dialog through which you can send us the logs.
