### ISSUE TITLE
1.14.4 iOS app crashes in iPhones.

### ISSUE THREAD

**Issue by antdude** [krille-chan/fluffychat#602]
### Bug Description

... Crashes after updating just now last night (USA's PDT). Uninstalling, redownloading, and reinstalling didn't fix it.

### Steps to Reproduce

1. Upgrade/Install v1.14.4 iOS app into iPhone.
2. Launch app, see its logo splash screen, and crash back to home screen.

### Expected Behavior

No crash.

### App Version

1.14.4

### Additional Platform Information

My and others' iPhones. Mine are 12 mini's iOS v16.7 and 6 +'s iOS v12.5.7.

**Comment by Titaniumtown** [comment]
I have a friend who can reproduce this same issue on iOS

**Comment by antdude** [comment]
Good. I am not alone. Hopefully, they can fix this issue and release a new version quickly!

**Comment by krille-chan** [comment]
I can now reproduce it on my iPhone SE2020 and I think I have a fix. Building a testfloght version soon

**Comment by antdude** [comment]
Good. I also see this issue in my very old  iPhone 6+'s iOS v12.5.7. It seems to be happening in all iPhones and iOS versions?

**Comment by Secure-Trust-Center** [comment]
same behaviour on my  iPad Pro 5. generation (16.6.1) and iPhone 14 (iOS 16.6.1) since FluffyChat v 1.14.4

**Comment by KnottyLorri** [comment]
I have issue on 2020SE.  iPads are ok though (thankfully)

**Comment by antdude** [comment]
Just got the updated app. It works! Thanks!

**Comment by marc-leinweber** [comment]
For me, it still crashes instantly on an iPhone 8, Fluffychat 1.14.5 and iOS 16.7.

**Comment by antdude** [comment]
Yeah, this bug was fixed long ago. :)
