### ISSUE TITLE
Can’t play WhatsApp bridged voice messages

### ISSUE THREAD

**Issue by pmffromspace** [krille-chan/fluffychat#603]
### Bug Description

Can’t play WhatsApp bridged voice messages

### Steps to Reproduce

Try to play a WhatsApp bridged voice message 

### Expected Behavior

Should play

### App Version

1.14.4

### Additional Platform Information

iPhone 13

### Additional Context

Since a year :/

**Comment by krille-chan** [comment]
Is it possible that you use the bridge on an android device? Please make sure to use an iOS device for the bridge if you are using fluffychat on an iPhone. Otherwise there will be codec problems
