### ISSUE TITLE
reduce size of Android release APK by splitting per ABI

### ISSUE THREAD

**Issue by warren-bank** [krille-chan/fluffychat#606]
### Feature Description

Hi. I'm not super familiar with Flutter, but it appears that:
* [this](https://github.com/krille-chan/fluffychat/blob/v1.14.5/.github/workflows/release.yaml#L67) is the build step to produce the release APK
* [Flutter docs](https://docs.flutter.dev/resources/faq#how-big-is-the-flutter-engine) suggest that the size of the Flutter engine is around 4.5 MB per ABI
  - rather than a universal build that includes every ABI,<br>a CLI flag can be used to produce one APK per ABI:<br> `flutter build apk --release --split-per-abi`
* doing some back-of-the-napkin maths..<br>this should produce 4x APKs (rather than 1) that are each approx. 63 MB:
  - 76.5 MB - (3 * 4.5 MB)
  - which is still horrendously large..<br>maybe there are other optimizations that could reduce the final size?

### Rationale

Bigger isn't always better..

**Comment by MadTooth** [comment]
hehe
