### ISSUE TITLE
A way to hide the side bar on the right 

### ISSUE THREAD

**Issue by I-like-stuff** [krille-chan/fluffychat#607]
### Feature Description

can you add a way to simply hide the bar on the right ( one that simply displays information about the room ) without the need to reside the app's window 

### Rationale

the room info side-bar takes about a chunk from the app's window when in chat rooms, I find it rather irritating

**Comment by toni-do** [comment]
I have same issue. I use fdroid Version 1.15.1 on all devices. In the chat, clicking the name of the receiving account expands the "Chat details" overview. On one device, this overview cannot be collapsed.

**Comment by vansoest** [comment]
same issue here

**Comment by toni-do** [comment]
Seems it is a Scaling issue. On my Samsung device, increasing the Zoom has fixed issue:
From Settings, tap Display. Swipe to and tap Screen zoom, and then adjust the slider at the bottom.
