### ISSUE TITLE
WebM video not properly displayed

### ISSUE THREAD

**Issue by Titaniumtown** [krille-chan/fluffychat#610]
### Bug Description

Attempting to view a webm file results in only the audio being played as the file is recognized as a audio-exclusive format.

### Steps to Reproduce

1. View Webm file in fluffychat
2. It says audio file even though it's a video
3. Clicking on it plays audio

### Expected Behavior

A video should play

### App Version

1.14.3

### Additional Platform Information

Android and Linux

**Comment by TLCPlusPlus** [comment]
I have the same issue when trying to send a video formatted webm, except it fails to send. Going back out of the conversation insists it's an audio file. Even has the audio player open, but cant play it since the file hasn't been sent.
