### ISSUE TITLE
Separate Direct Chats and Groups doesn't work right after launching the app

### ISSUE THREAD

**Issue by tux93** [krille-chan/fluffychat#614]
### Bug Description

When "Separate Direct Chats and Groups" is enabled and Fluffy is started (when it was no longer active in the background) it opens in the Direct Chats tab but the chat list contains DMs as well as Groups.

Only after switching to the Groups tab and back to DMs once does the separtion work.

I first noticed this behaviour after updating to 1.14.0 but it is still present in 1.14.4

### Steps to Reproduce

1. Enable "Separate Direct Chats and Groups" in Chat Settings
2. Close the app so it no longer is active in background
3. Open the app
4. The Direct Chats tab contains both DMs and Groups
5. Switch to Groups tab and back, now the separation works until the app is closed again

### Expected Behavior

The Direct Messages tab only contains DMs from the start.

### App Version

1.14.4

### Additional Platform Information

OnePlus 8, LineageOS 20, Fluffy installed from F-Droid

**Comment by olly1240** [comment]
This happens also on iOS in the latest AppStore version 1.14.5

**Comment by Titaniumtown** [comment]
I can reproduce on Android and Linux

**Comment by es-ka** [comment]
I can confirm this. At least versions 1.14.3. and 1.14.4 from Fdroid on Android/LineageOS 18 are affected.

**Comment by Sir-Photch** [comment]
I can confirm this

**Comment by tux93** [comment]
Closing this as it now works with v1.15.1 and v1.16.0
