### ISSUE TITLE
The setting "Hide unimportant state events" does not persist across restarts

### ISSUE THREAD

**Issue by jivanpal** [krille-chan/fluffychat#615]
### Bug Description

The setting [Chat] > [Hide unimportant state events] works correctly immediately after being enabled/disabled. However, if it is disabled and the app is restarted, then:

- the setting reverts to enabled; and
- in the [Chat] settings page, the setting is briefly visible in the "enabled" state, but then immediately switches to the "enabled" state. Despite this visual bug, the app still functions as if the setting is enabled.

### Steps to Reproduce

1. Go to [Settings] > [Chat].
2. Toggle [Hide unimportant state events] so that it is disabled ("unimportant" state events will be shown).
3. Restart the app.
4. Go to Settings > Chat. Notice that the setting initially appears enabled, but then switches to appearing disabled.
5. Go back and view any chat room. Notice that "unimportant" state events are not shown, despite the apparent user setting.

### Expected Behavior

The setting should correctly persist across app restarts.

### App Version

1.14.4 via Google Play

### Additional Platform Information

Android 9.0 (Samsung One UI 1.0) on Samsung Galaxy A8 (2018) (vendor ID A530F/DS)

**Comment by krille-chan** [comment]
This should be fixed in newest version. Thank you very much for reporting it
