### ISSUE TITLE
[Feature request] Support for disabling notifications for this Fluffychat session/device

### ISSUE THREAD

**Issue by jivanpal** [krille-chan/fluffychat#616]
### Feature Description

The settings currently has a toggle for notifications on the Matrix account level. However, the user may want to have this enabled in general, but not have this sessions receive/display notifications. Effectively, this would be a way to remove Fluffychat's entry from Notification > Devices permanently, and revert this choice, at will.

For reference, Element Android implements this as: Settings > Notifications > Enable notifications for this session

### Rationale

Currently, the user can effectively disable notifications through other means (e.g. via the Android app's OS-level permissions to display notifications), but it would be nice to save bandwidth by not having a persistent connection open for push notifications, in case the user doesn't want to receive any in the first place.

### Additional Context

Potentially related to #532.

**Comment by kraftnix** [comment]
this is still important to me as an admin who doesn't use fluffychat primarily on android but needs to test it for users
