### ISSUE TITLE
[Feature request] Android Notification groups

### ISSUE THREAD

**Issue by jivanpal** [krille-chan/fluffychat#617]
### Feature Description

It would be nice if notifications from different rooms were [grouped into a single notification](https://developer.android.com/develop/ui/views/notifications/group). so that there aren't several Fluffychat icons in the top bar, and so that the notification drawer is cleaner by being able to collapse all Fluffychat notifications down into a single row.

### Rationale

This would prevent several Fluffychat icons from appearing in the top bar (one for each notification), and also make the notification drawer cleaner by being able to collapse all Fluffychat notifications down into a single row.

**Comment by SteffoSpieler** [comment]
Yes, this would be so great! Currently it seems like FluffyChat's notifications aren't like "typical" messenger notifications...

It would be great if this could be implemented!
