### ISSUE TITLE
[Feature request] Hide your profile picture checkbox on chat settings

### ISSUE THREAD

**Issue by mips64-el** [krille-chan/fluffychat#618]
### Feature Description

A checkbox on chat settings called "Hide your profile picture" 

- This checkbox will be enabled by default.
- If this checkbox is disabled you will be able to see your profile picture in each message group you send.
- If this checkbox is enabled the profile picture won't be displayed in each of your group messages, so it won't cause any different behavior from now.

### Rationale

It is nice to see your own profile while you chat

**Comment by krille-chan** [comment]
Thank you very much for sharing your idea. Unfortunately I disagree that such things should be configurable. This does not fit into the design vision of FluffyChat.
