### ISSUE TITLE
Fluffy Chat Web doesn't work on Tor Browser

### ISSUE THREAD

**Issue by sallyFoster** [krille-chan/fluffychat#628]
### Bug Description

Fluffy Chat Web doesn't load over Tor Browser

### Steps to Reproduce

Go to https://fluffychat.im/web/ on the Tor Browser

### Expected Behavior

Fluffy Chat Web should load over the Tor Browser

### App Version

v1.14.5

### Additional Platform Information

MacOS Sonoma 14

### Additional Context

![image](https://github.com/krille-chan/fluffychat/assets/104597302/dcf450be-e171-4e92-959a-016be6506603)

It just stays like this

**Comment by krille-chan** [comment]
Looks like the service worker API is not available in TOR browser. Therefore there is no way to fix it until the TOR browser enables this
