### ISSUE TITLE
Search through chat history

### ISSUE THREAD

**Issue by imxade** [krille-chan/fluffychat#629]
### Feature Description

Option to search through room's chat history

### Rationale

- So participants don't have to repeat/ask for same thing 
- to search for stuff that suddenly came to mind
- every messenger I've used till now has this feature

**Comment by tux93** [comment]
There already was an open issue for this: #9

**Comment by imxade** [comment]
My bad :( It didn't show up earlier.
Closing ...

**Comment by imxade** [comment]
closing

**Comment by imxade** [comment]
closing

**Comment by imxade** [comment]
closing
