### ISSUE TITLE
How to delete unsent messages

### ISSUE THREAD

**Issue by iacore** [krille-chan/fluffychat#632]
### Bug Description

unsent messages can't be deleted, and are always at the bottom of the room.

### Steps to Reproduce

1. Turn off Internet
2. Go to any DM
3. Send message
4. Wait until it fail to send

Now try to delete the red (unsent) message!

### Expected Behavior

I should be able to delete them.

### App Version

1.14.4

### Additional Platform Information

Android

**Comment by germain-gg** [comment]
I've also been experiencing the same thing.
Is there a way I can share logs that would be helpful to debug this issue?

**Comment by krille-chan** [comment]
Should be fixed in the upcomming version with a much more prominent delete button. Thanks for reporting. As a workaround in the meantime you can clear the cache with the chat command `/clearcache`  in any room.
