### ISSUE TITLE
Open chat when clicking notification

### ISSUE THREAD

**Issue by Fxsch** [krille-chan/fluffychat#636]
### Feature Description

Currently when tapping on a notification, it will simply open Fluffychat where you can see all the chats. I think it would make more sense if it opened the chat the notification is from.

### Rationale

When clicking a notification you'll usually manually go into the chat that notification is from anyway, so Fluffychat should open that chat automatically.

**Comment by krille-chan** [comment]
On Android this works fine. Which platform do you mean?

**Comment by Fxsch** [comment]
I meant Android but now it's working fine for me too
