### ISSUE TITLE
Crop image previews smarter

### ISSUE THREAD

**Issue by Fxsch** [krille-chan/fluffychat#637]
### Feature Description

Is there a way to crop image previews in a smarter way? The issue is that sometimes I get sent images that have nothing but a solid background color in the center, like screenshots, where there is text only at the top and it makes me think that there was an error downloading the image for a moment because the cropped preview only shows that background. 

If this were to be implemented, it could also be made so that pictures of people center the preview on their faces or pictures of some kind of object center on that.

The only way to implement this would be to use AI, I think. The app [WallFlow](https://github.com/ammargitham/WallFlow) has an option to use an AI model, that runs locally on the phone, to detect objects in an image and crop it in a way that centers that object.

### Rationale

Explained in the description already.

**Comment by gabrc52** [comment]
Hmmm I think AI would be overkill but I agree the current square cropped images aren't good when images have aspect ratios that are nonsquare

**Comment by gabrc52** [comment]
Issue persists.
