### ISSUE TITLE
missing library in binary release 1.15.0-1.15.1

### ISSUE THREAD

**Issue by pirate486743186** [krille-chan/fluffychat#640]
### Bug Description

i get this error, it requires a newer libstdc++
> /usr/bin/fluffychat: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /usr/libexec/fluffychat/lib/libdesktop_drop_plugin.so)

(yea, i moved them)

### Steps to Reproduce

Try running the release on Debian 12

### Expected Behavior

it should just work

### App Version

1.15.0

### Additional Platform Information

Debian 12

**Comment by krille-chan** [comment]
Hey, thanks for opening the issue. I would suggest to use the official way to install the app via snap. Here is a tutorial how you can do this on Debian: https://snapcraft.io/install/fluffychat/debian

if you want to use the binary output from the CI directly you have to bring your own dependencies
