### ISSUE TITLE
Unable to pin others messages

### ISSUE THREAD

**Issue by tux93** [krille-chan/fluffychat#649]
### Bug Description

As a room admin I used to be able to pin messages from anyone, with current FluffyChat the pin button only shows up for my own messages.

### Steps to Reproduce

1. Open a chat you're admin in
2. Long press someone else's message
3. The Pin button is not shown
![Screenshot_20231106-133142_FluffyChat](https://github.com/krille-chan/fluffychat/assets/1749593/b87fdd32-20ed-410d-8b3a-218b9140cd37)
4. Long press one of your own messages
5. The Pin button is shown
![Screenshot_20231106-133113_FluffyChat](https://github.com/krille-chan/fluffychat/assets/1749593/bd7d590c-b365-497b-8ee1-04edd991f135)

### Expected Behavior

As admin / moderator any message can be pinned

### App Version

1.15.0

### Additional Platform Information

OnePlus 8, LineageOS 20, Fluffy installed from F-Droid

**Comment by Janavanwalde** [comment]
Ok, thanks for the message. We'll fix this immediately.

**Comment by Janavanwalde** [comment]
OK, it's been fixed. This will be fixed in the new release.
