### ISSUE TITLE
cannot grant Admin - silent failure

### ISSUE THREAD

**Issue by strk** [krille-chan/fluffychat#656]
### Bug Description

When I try to grant admin to a user on a different homeserver the operation fails silently

### Steps to Reproduce

Go to room setting, partecipants, long tap a name, change permission level, pick admin

### Expected Behavior

User gets admin or an error message is shown

### App Version

1.15.0

### Additional Platform Information

android

**Comment by bitnapper** [comment]
I have the exact same error on iOS 17.1.1 with latest fluffy chat.
