### ISSUE TITLE
Fluffychat encrypts messages to unverified devices in end-to-end encrypted rooms by default

### ISSUE THREAD

**Issue by andidr** [krille-chan/fluffychat#660]
### Bug Description

When a new device joins a room with end-to-end encryption enabled, Fluffychat encrypts new messages sent to the room to the new device despite a missing verification of the new device. This moves trust from end-users / devices to the server, as anyone in possession of the login credentials of a user is able to join end-to-end encrypted rooms with a new device and receive new messages. Other clients (e.g., Element) provide an option "encrypt to verified sessions" only to prevent this.

### Steps to Reproduce

1. Register two new users A and B at your homeserver
2. Log in to your homeserver with A and B, start a direct chat and verify the users
3. Log off B from the homeserver
4. Use a new device to log in to your homeserver as B
5. Write a message from A to the room associated with the direct chat

### Expected Behavior

Fluffychat should not encrypt the message for B's new device, since it hasn't verified that device, yet.

### App Version

1.15.0

### Additional Platform Information

Android

### Additional Context

This may be related to Issue #251 filed for the web version.

**Comment by TheOneWithTheBraid** [comment]
Should be related to the [Client(shareKeysWithUnverifiedDevices)](https://pub.dev/documentation/matrix/latest/matrix/Client/Client.html) parameter in the SDK.

**Comment by krille-chan** [comment]
> Fluffychat should not encrypt the message for B's new device, since it hasn't verified that device, yet.

That's wrong. A matrix client must not share keys with devices which are blocked. Preventing the client to share keys with non-blocked devices which are not verified yet, is a client-choice (could be made a user choice in the future). But preventing this will make the app unusable for most users who do not understand the basic concepts of end to end encryption. If you do not want to share messages with unverified devices, just block them in the encryption page. You get informed by the encryption-button if new unverified devices enter the room
