### ISSUE TITLE
[BUG]: Error Widget

### ISSUE THREAD

**Issue by EpicKiwi** [krille-chan/fluffychat#661]
### Bug Description

- Operating system: android
- Version: 1.15.0

### Exception
Provider<MatrixState> not found for NewPrivateChat

### StackTrace
#0      Provider._inheritedElementOf (package:provider/src/provider.dart:343)
#1      Provider.of (package:provider/src/provider.dart:293)
#2      Matrix.of (package:fluffychat/widgets/matrix.dart:56)
#3      LoadProfileBottomSheet.build (package:fluffychat/pages/user_bottom_sheet/user_bottom_sheet.dart:37)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:5367)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5297)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#7      StatelessElement.update (package:flutter/src/widgets/framework.dart:5373)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#11     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
#15     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3685)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dar

### Steps to Reproduce

1. Tap "new conversation" button
2. Type someone's name
3. Type "send messages" button to start a conversation

### Expected Behavior

Not showing an error

### App Version

1.15.0

### Additional Platform Information

Device: Pixel 4a OS: Android (calyxos)

### Additional Context

Google services : MicroG
Installed from F-droid

**Comment by krille-chan** [comment]
Should be fixed now :) Please reopen if it happens again

**Comment by EpicKiwi** [comment]
Thank you a lot !
