### ISSUE TITLE
Not able to add group chats

### ISSUE THREAD

**Issue by techrivertree** [krille-chan/fluffychat#662]
### Bug Description
ETA: I used chat instead of looking for group, my bad. I cannot join the fluffy chat group.

Version 1.15

*I am still new to Fluffychat*

I am trying to join the group for fluffychat (lol).
I copied the identifier (#fluffychat:matrix.org)

Fluffychat cannot find any groups with that identifier

### Steps to Reproduce

1. Open fluffychat
2. Search for #fluffychat:matrix.org
3. Click on group icon
4. fluffychat group summary is listed, shows 2600 participants.
5. Click join room
6. Nothing happens, wont allow me to join room.,

### Expected Behavior

Using the identifier #fluffychat:matrix.org should allow me to join the fluffychat matrix group.

### App Version

1.15

### Additional Platform Information

Ubuntu 23.04

### Additional Context

If I am doing something wrong please be easy on me, I am still learning to use fluffychat.

**Comment by Janavanwalde** [comment]
Hello, can't reproduce it. Do you have any further information?

**Comment by techrivertree** [comment]
My initial post was wrong, I tried to a chat instead of a group. Same error occurs though

Identifier: #fluffychat:matrix.org
Load fluffychat, search for "#fluffychat:matrix.org"
Fullychat will find the group. 
Click on the group icon
Summary of fluffychat is listed, shows 2600 participants.
Click Join
Nothing happens.
![Screenshot from 2023-11-11 17-31-46](https://github.com/krille-chan/fluffychat/assets/69227859/92a80520-db37-41db-b058-f0d6a0b07f5f)

I tried to find another fluffychat group, identifier could not find any groups.

**Comment by techrivertree** [comment]
Could it be that 2600 is the max group size?

**Comment by techrivertree** [comment]
Since I last posted a screenshot of the join room bug, 40 people have joined the fluffychat group. 
![Screenshot from 2023-11-29 21-54-40](https://github.com/krille-chan/fluffychat/assets/69227859/b4f373fa-e60c-4e2b-859c-bbcc2f2aea30)

**Comment by LFd3v** [comment]
As of v1.16.0, FluffyChat shows the same error when trying to join a group from the search results:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Provider<MatrixState> not found for PublicRoomBottomSheet
#0      Provider._inheritedElementOf (package:provider/src/provider.dart:343)
#1      Provider.of (package:provider/src/provider.dart:293)
#2      Matrix.of (package:fluffychat/widgets/matrix.dart:59)
#3      PublicRoomBottomSheet._joinRoom (package:fluffychat/widgets/public_room_bottom_sheet.dart:31)
#4      PublicRoomBottomSheet.build.<anonymous closure> (package:fluffychat/widgets/public_room_bottom_sheet.dart:98)
#5      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309)
#9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279)
#10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167)
#11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:492)
#12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468)
#13     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:439)
#14     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413)
#15     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376)
#16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323)
#17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292)
#18     _invoke1 (dart:ui/hooks.dart:328)
#19     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:410)
#20     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)
```

It is not possible to join a group from the New Chat dialog anymore. Joining a group found inside a space works tho.

**Comment by LFd3v** [comment]
> FluffyChat shows the same error when trying to join a group from the search results

Just for the record, as of v1.17.1, joining groups from the search results works fine.
