### ISSUE TITLE
UI for changing password is confusing

### ISSUE THREAD

**Issue by gera2ld** [krille-chan/fluffychat#663]
### Bug Description

![image](https://github.com/krille-chan/fluffychat/assets/3139113/ffaeb92c-aa27-47f5-a5c4-5dddd7b9fffc)

The UI indicates that both input boxes are for the new passwords. But I got "No permission" error after typing the new password twice.

After checking the logs, I found that the first input is for the old password, and the second for the new password.

It happens to both web and Android clients.

### Steps to Reproduce

1. Log in to web or Android client
2. Go to Settings > Security > Change Password
3. Input the new password twice
4. Get "No permission" error

### Expected Behavior

Change password successfully

### App Version

1.15.0

### Additional Platform Information

web and Android

**Comment by techrivertree** [comment]
I have the same error.

Logs
# [DEBUG] Error parsing push rule Instance of 'PushRule' - Exception: Unknown push condition: event_event_property_contains
# [DEBUG] Error parsing push rule Instance of 'PushRule' - Exception: Unknown push condition: event_property_is
# [DEBUG] Error parsing push rule Instance of 'PushRule' - Exception: Unknown push condition: event_property_is
