### ISSUE TITLE
Double tapping on an image does not zoom in

### ISSUE THREAD

**Issue by gabrc52** [krille-chan/fluffychat#665]
### Bug Description

After opening an image, double tapping does not zoom in. Instead it does nothing.

### Steps to Reproduce

1. Receive or send an image
2. Tap on it
3. Double tap on it

### Expected Behavior

The image zooms in

### App Version

1.15.0

### Additional Platform Information

Android 13 on Pixel 6

### Additional Context

Element, WhatsApp, etc have this behavior. It might be an Android-specific platform behavior but certainly expected by Android users.

**Comment by gabrc52** [comment]
I can still reproduce this issue

**Comment by krille-chan** [comment]
Will be solved upstream: https://github.com/flutter/flutter/issues/64156 so I don't think it is worth to put much effort in this here

**Comment by CeruleanDerpo** [comment]
It's been 2 years and the issue still occurs

**Comment by gabrc52** [comment]
Then please bump the upstream issue

**Comment by CeruleanDerpo** [comment]
Oh sorry
