### ISSUE TITLE
Custom reactions are no longer rendered

### ISSUE THREAD

**Issue by tux93** [krille-chan/fluffychat#675]
### Bug Description

With current FluffyChat custom reactions, both custom emoji as well as those created with `/react`, are no longer rendered.

### Steps to Reproduce

1. Open a chat in Fluffy and react to a message with the `/react` command
2. The reaction is not visible in Fluffy
3. Open the same chat in a different Client, e.g. Cinny
4. The reaction is visible there

### Expected Behavior

The reaction is visible within FluffyChat as well.

### App Version

1.15.0

### Additional Platform Information

OnePlus 8, LineageOS 20, Fluffy installed from F-Droid

**Comment by krille-chan** [comment]
Thanks for the report. Unfortunately I cannot reproduce this. Do you have more information?

![Bildschirmfoto vom 2023-11-19 09-46-37](https://github.com/krille-chan/fluffychat/assets/24619905/fadea4f6-a1cb-4298-bf60-07fcf5510df3)

**Comment by tux93** [comment]
I can no longer reproduce the `/react` part either, maybe that fixed itself in 1.15.1

However reactions that contain custom emoji are still invisible:
![Screenshot_20231119-160136_FluffyChat](https://github.com/krille-chan/fluffychat/assets/1749593/645d1d60-393a-4817-af55-fcf14f431cb6)

Same message in Cinny:
![Screenshot_2023-11-19_16-02-03](https://github.com/krille-chan/fluffychat/assets/1749593/d49b327f-fc73-458a-8f4d-5611de189081)


I believe there was a Issue about this before but I can't seem to find it anymore, maybe it got lost in the migration to from GitLab.

**Comment by tux93** [comment]
Custom emoji reactions are still not rendered in v1.16.0

**Comment by Akselmo** [comment]
This seems still to be an issue in v1.17.0

**Comment by tux93** [comment]
#485 sounds like it would fix this

**Comment by Akselmo** [comment]
Still seems to be broken on v1.18.0.

This happens in the Android app with custom emoji reactions.

**Comment by Akselmo** [comment]
Seems to still be an issue in v1.20.0 on android

Anything i can do to help to fix this issue?

It happens in situations where i have bridges from discord to matrix for example.

It can also happen if anyone reacts to someones message with matrix emote that is just mxc link. 

I think the linked PR would fix it.

**Comment by Akselmo** [comment]
I commented repro steps to the linked pr

**Comment by tux93** [comment]
Works in 1.21.0
