### ISSUE TITLE
clean room / remove all messages

### ISSUE THREAD

**Issue by paulcarroty** [krille-chan/fluffychat#678]
### Feature Description

Will be nice to have one button for this on top right, near the the delete button.

### Rationale

It's painful to remove long chats.

**Comment by paulcarroty** [comment]
bump

**Comment by krille-chan** [comment]
Thats done automatically when all participants leave a room and the delete it from the archive

**Comment by paulcarroty** [comment]
I don't want to **leave** room, just remove old messages.
