### ISSUE TITLE
Crash on iOS due to (bad?) image format

### ISSUE THREAD

**Issue by LFd3v** [krille-chan/fluffychat#683]
### Bug Description

As the title says, trying to join or open a room with the image visible in the message history causes a crash.

### Steps to Reproduce

Not much to say, besides that joining the room while the image is visible causes the crash instantaneously. Also trying to join the room causes the crash.

### Expected Behavior

No crash, as it works on v1.15.1 on Linux.

### App Version

1.15.0

### Additional Platform Information

iPhone 11 iOS 15.7

### Additional Context

Message content related to the image (got with FluffyChat v1.15.1 on Linux):

```
{
    "content": {
        "body": "Screenshot_2023-11-17_at_3.10.42_PM.png",
        "external_url": "https://cdn.discordapp.com/attachments/992481376278421595/1175045362415845446/Screenshot_2023-11-17_at_3.10.42_PM.png?ex=6569cd45&is=65575845&hm=cc46b05fda1e14b0345b1d8fb5ad28c654f7758ef2c181750e13ef424f2f6ab8&",
        "info": {
            "h": 24,
            "mimetype": "image/png",
            "size": 13846,
            "w": 1920
        },
        "msgtype": "m.image",
        "url": "mxc://t2bot.io/e20fa71fe1af2637030e1749ab698c267f910fb41725486634557767680"
    },
    "type": "m.room.message",
    "event_id": "$1NPKHL3cKWn9L2Eav5aigJYtauKP3C2lZ36lXZ_vrpI",
    "room_id": "!cslAxTXdSqYKHOqlbY:matrix.org",
    "sender": "@_discord_934518833824292925:t2bot.io",
    "origin_server_ts": 1700223046435,
    "unsigned": {
        "com.famedly.famedlysdk.message_sending_status": 2
    }
}
```

I get this error in the log when using v1.15.1 on Linux, but no crash and I can see the image in the chat:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Codec failed to produce an image, possibly due to invalid image data.
```

PS: Not sure when I will get v1.15.1 on iOS, but I will try to reproduce the crash with the newer version and close this if it does not happen.

**Comment by krille-chan** [comment]
Thanks for the report.
I was able to reproduce this on Linux with a different error: 

```
════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter_blurhash/src/blurhash_widget.dart': Failed assertion: line 28 pos 16: 'decodingHeight != 0': is not true.
```

I have fixed this. Will test it on my iPad now...

**Comment by LFd3v** [comment]
I could not provide logs for the iOS version because it is cleared when the app starts, so the error related to the crash is gone...

Thank you, and thank you for FluffyChat!

**Comment by LFd3v** [comment]
Using v1.16.0 on iOS I am able to view the thumbnail and open the image that caused the crash in the OP, so I guess it is fixed.

Thanks again and thank you a lot for FluffyChat!
