### ISSUE TITLE
Unable to verify users using other Matrix Clients

### ISSUE THREAD

**Issue by jahway603** [krille-chan/fluffychat#686]
### Bug Description

I see many messages with `"Could not decrypt message: This can happen ...`, which means that verification has to happen between Matrix protocol clients. When I click on someone else's username with the intention to "verify" them, there is no option in Fluffychat to verify.

### Steps to Reproduce

1. Enter a room where I see error message of `"Could not decrypt message: This can happen ...`
2. Click room name at top to display user list.
3. Click on user account I want to verify.
4. There is no option there to verify, so can never get rid of the `"Could not decrypt message: This can happen ...` error message.

### Expected Behavior

To verify any user that's using a different Matrix protocol client.

### App Version

1.15.1

### Additional Platform Information

Android

**Comment by krille-chan** [comment]
The verification button is in the Encryption page in a DM room. This seems to be a UX problem and not a bug
