### ISSUE TITLE
message type file cannot be downloaded on android 10

### ISSUE THREAD

**Issue by aryanA101a** [krille-chan/fluffychat#694]
### Bug Description

Something went wrong:  - PathAccessException: Cannot open file, path = '/storage/emulated/0/Download/(1)Feedback Report.pdf' (OS Error: Permission denied, errno = 13)

### Steps to Reproduce

1. Open fluffy chat on Android 10 or less
2. Receieve a pdf or docx
3. Tap on the recieved file

### Expected Behavior

The file should be downloaded and stored to download folder.

### App Version

1.15.1

### Additional Platform Information

Android 10

**Comment by krille-chan** [comment]
Can you try again with 1.17.1? The logic to find the download directory has been improved there
