### ISSUE TITLE
Video upload

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#70]
#### Description
Uploading a photo is easy but uploading a video seems impossible, can't access the the gallery for video's.

#### To Reproduce
1. Click on the + button and try to select a video
2. From the gallery select a video to share and Fluffy chat is not there

#### Additional information:
- Device: iPhone 11 Pro Plus
- OS and OS version: 14.5.1
- Installed version of FluffyChat: 0.30.3

/issue fluffy

**Comment by wcjord** [comment]
@krille-chan It seems that this could be split into two tickets.

1) Feature request to, within fluffyChat and the options accessible via the '+' icon in the input bar, select a video from a user's gallery as opposed to "open the camera for a video" and directly filming the video within FluffyChat
2) Feature request to share from share options in the native photo gallery.
