### ISSUE TITLE
"Reopen chat" leaves room without notice

### ISSUE THREAD

**Issue by LukeLR** [krille-chan/fluffychat#728]
### Bug Description

At first, thanks for all your efforts. FluffyChat is my main chat application, this is awesome work!

However, I was caught off-guard that the "Reopen chat" feature leaves the current chat room. Yesterday, someone accidentally left a direct chat with me. I wanted to re-add them, but the room details didn't allow me to invite members (as it's a direct chat, I suppose). So I clicked the "Reopen chat" button at the bottom of the room. What I didn't expect was that while it creates a new room with that person, it removes my account from that direct chat as well, without notice.

I don't think that "Reopen chat" makes it clear enough that it makes me leave that room as well. If I had known that, I certainly wouldn't have done it, as now the room with all its messages is gone forever. While in my eyes the best option would be to re-add the other user to the old room, I'd vote for at least asking for confirmation before leaving the room.

### Steps to Reproduce

1. Have a direct chat with another user
2. Have that user leave the direct chat
3. Click the "Reopen chat" button at the bottom of the screen
4. Notice that the current account has left the room as well.

### Expected Behavior

The app re-adds the user to the current room or at least asking for confirmation before leaving the room.

### App Version

1.16.0

### Additional Platform Information

Fairphone 5 /e/-OS 13

**Comment by krille-chan** [comment]
Has been fixed in 1.17.0🥳
