### ISSUE TITLE
tg-forward not rendered 

### ISSUE THREAD

**Issue by officialdakari** [krille-chan/fluffychat#730]
### Bug Description

tg-forward HTML tag is not rendered
![Screenshot_20231218-115726](https://github.com/krille-chan/fluffychat/assets/65029993/bd5fd9f7-441f-4355-83fb-0bd457f7005d)

### Steps to Reproduce

Open message with tg-forward

### Expected Behavior

tg-forward should be rendered 

### App Version

1.16.0

### Additional Platform Information

Android, BV9200

**Comment by DarkCoder15** [comment]
up

**Comment by DarkCoder15** [comment]
Still not fixed after update!
