### ISSUE TITLE
FluffyChat requires "_matrix/client/r0/login" for SSO with MAS

### ISSUE THREAD

**Issue by beposec** [krille-chan/fluffychat#732]
### Bug Description

When trying to login in via SSO with matrix-authentication-service fluffychat fails with "Unrecognized request".
The reverse proxy log shows that fluffychat tries to access the following URIs:
```
/_matrix/client/versions
/_matrix/client/v3/login
/_matrix/client/r0/login
```

When not forwarding the r0 URI to the MAS, Login fails. But for me it seems that r0 is not part of the currenct spec, so it shouln't be a requirement:
https://spec.matrix.org/v1.9/client-server-api/

### Steps to Reproduce

Login with Fluffychat to an Synapse with MAS with only forwarding the v3/login URI.

### Expected Behavior

Login should work.

### App Version

1.16.0

### Additional Platform Information

iPhone 13 Mini

**Comment by krille-chan** [comment]
I've updated the manual endpoints to v3. Please check it when the next release comes out

**Comment by beposec** [comment]
Fixed. Only v3 is requested now. Thanks!
