### ISSUE TITLE
recent update (?) automatically opens chat after notification receieved ANNOYING AF 

### ISSUE THREAD

**Issue by tehoblivious** [krille-chan/fluffychat#737]
### Bug Description

as title says 

must've been a recent update some time 

i'd get an update 

then just out of nowhere it would act as if i opened the notification opening the chat

of course making it look like i read the chat when i wasn't ready for it 

making me really feel not using this client of matrix anymore 

please fix it's a "game breaking bug" 

I can't have chats automatically open when i'm not ready to read them yet, that's just plain broken. 

### Steps to Reproduce

get notification
unlock phone
may or may not automatically open 
unlock phone again
chat probably automatically opens (without me clicking it) 

### Expected Behavior

IT'S NOT SUPPOSED TO ACT LIKE I clicked it 

### App Version

1.16.0

### Additional Platform Information

android 14 calyxOS 5.2.0 google pixel 5 5G

**Comment by krille-chan** [comment]
First of all: Please watch out for your tone. This project is completely driven by volunteers. Also it's helpful if your issue description would use some uppercase letters and punctuation marks.

Besides that I cannot reproduce your bug. Please provide better steps to reproduce it. I tried:

- Pause app (move it into the background but not terminate it)
- Receive notification for room X and tap on it
-> App opens in the room X as expected
- Terminate app
- Open app again
-> App does **not** open room X as expected

Same if I start the process with app terminated.

**Comment by blackdotraven** [comment]
Hi @krille-chan
i installed Fluffychat some days ago and i have a similar problem.
After i got a notification on Fluffychat there is like a 50/50 chance that this chat will be open on my phone without me clicking the notitifcation.
The app is always in the background when i close my phone.

What would be the best way to gather information that could help you or some other developher working on this project?
