### ISSUE TITLE
Prohibit skipping email when creating account via matrix.org

### ISSUE THREAD

**Issue by LilithHafner** [krille-chan/fluffychat#751]
### Feature Description

Prohibit skipping email when creating account via matrix.org

### Rationale

Currently, when creating an account at the matrix.org domain, the GUI allows a user to skip providing an email. However account creation then fails. It would be better to require that step eagerly for that domain.

**Comment by krille-chan** [comment]
Creating an account is not possible anymore from FluffyChat anyway so I'll close this issue

**Comment by LilithHafner** [comment]
I just created an account on Matrix.org through the FluffyChat UI, version 1.12.0

```
x@fedora:~$ flatpak info im.fluffychat.Fluffychat

Fluffychat - Chat with your friends

          ID: im.fluffychat.Fluffychat
         Ref: app/im.fluffychat.Fluffychat/aarch64/stable
        Arch: aarch64
      Branch: stable
     Version: 1.12.0
     License: AGPL-3.0-only
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 75.4 MB
     Runtime: org.freedesktop.Platform/aarch64/22.08
         Sdk: org.freedesktop.Sdk/aarch64/22.08

      Commit: 1d86664868daeacda28d677fa1acd25eb77193d76771a08a181534f95847de61
      Parent: 7a23631b308875a1d9a0318b54b3dd6c24c2b8b2c8e1daf47579edb5eefb00d2
     Subject: Update 2 modules (a6a0b01a)
        Date: 2023-06-12 08:09:24 +0000
```

Can send screen recording of creating another account if you would like.
