### ISSUE TITLE
Send button does not appear 

### ISSUE THREAD

**Issue by krtko1** [krille-chan/fluffychat#752]
### Bug Description

After recent update send button sometimes doesn't appear after I start writing message.

https://github.com/krille-chan/fluffychat/assets/21214184/63b57d88-5348-44e1-a55a-5ea4825b4e64

Usually it happens after sending one message correctly. Defocus and refocus od messagebox resolves problem.

More common in messenger bridge chats.

### Steps to Reproduce

1. go to chat
2. send one message
3. continue to write another message

### Expected Behavior

microphone button should change to send button 

### App Version

1.16.1

### Additional Platform Information

Device: Mi 8 pro, OS: LinageOS 20 (Android 13), LinageOS version: 20-20231205-NIGHTLY-equuleus, Gboard version: version 13.6.11.574113912-release-arm64-v8a

**Comment by krille-chan** [comment]
Thanks, fixed in main branch
