### ISSUE TITLE
[BUG]: Unable to load timeline

### ISSUE THREAD

**Issue by phs-66** [krille-chan/fluffychat#763]
- Operating system: android
- Version: 1.17.0

### Exception
type 'List<dynamic>' is not a subtype of type 'List<String>' of 'other'

### StackTrace
#0      ListBase.+ (dart:collection/list.dart:345)
#1      MatrixSdkDatabase.getEventList.<anonymous closure> (package:matrix/src/database/matrix_sdk_database.dart:431)
<asynchronous suspension>
#2      Room.getTimeline (package:matrix/src/room.dart:1461)
<asynchronous suspension>
#3      ChatController._getTimeline (package:fluffychat/pages/chat/chat.dart:333)
<asynchronous suspension>
#4      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:624)
<asynchronous suspension>

**Comment by krille-chan** [comment]
Fixed in 1.17.1🥳
