### ISSUE TITLE
[BUG]: Error Widget

### ISSUE THREAD

**Issue by johnandmegh** [krille-chan/fluffychat#770]
Happened when I tried to jump to the last read message

- Operating system: linux
- Version: 1.17.0

### Exception
RangeError (index): Invalid value: Not in inclusive range 0..29: 99

### StackTrace
#0      List.[] (dart:core-patch/growable_array.dart:264)
#1      ChatEventList.build.<anonymous closure> (package:fluffychat/pages/chat/chat_event_list.dart:106)
#2      SliverChildBuilderDelegate.build (package:flutter/src/widgets/scroll_delegate.dart:490)
#3      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:829)
#4      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:843)
#5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2835)
#6      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:835)
#7      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349)
#8      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2657)
#9      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1071)
#10     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2657)
#11     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338)
#12     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:486)
#13     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:239)
#14     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:281)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#16     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139)
#17     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:361)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
#19     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:601)
#20     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1554)
#21     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1463)
#22     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385)
#23     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025)
#24     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038)
#25     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591)
#26     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986)
#27     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457)
#28     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#29     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255)
#30     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
#31     _invoke (dart:ui/hooks.dart:312)
#32     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
#33     _drawFrame (dart:ui/hooks.dart:283)

**Comment by krille-chan** [comment]
Thank you so much :) fixed with latest commit
