### ISSUE TITLE
Use corresponding icons on hover for selecting chats and messages

### ISSUE THREAD

**Issue by ggurdin** [krille-chan/fluffychat#771]
### Feature Description

When hovering over chat list items and messages, two different icons are shown (a checkbox and an ellipsis), both of which are used to select the item being hovered over. It would be nice if these used the same icon, to indicate that they do similar things.

### Rationale

Hello! With the recent updates, there is now an ellipsis icon when hovering over messages that can be clicked to select the message. There is also a checkbox icon when hovering over chats in the chat list, that can also be clicked to select the given chat. It may be more intuitive for these two mechanisms to use the same icon. It's slightly confusing to see the checked box when hovering over a chat – I initially thought this meant something had been completed within the chat. The ellipsis icon on the hovered messages made sense immediately.

**Comment by krille-chan** [comment]
Ah, I haven't found the perfect solution for this yet...
