### ISSUE TITLE
URL too long when reporting bug 

### ISSUE THREAD

**Issue by JAicewizard** [krille-chan/fluffychat#772]
### Bug Description

When using the in app report feature, github complains the URL is to long 

### Steps to Reproduce

1. Hit a widget crash
2. Click report
3. See error 

### Expected Behavior

It should open a URL that is not to long, as this defeats the report feature 

### App Version

1.17.0

### Additional Platform Information

-

**Comment by krille-chan** [comment]
Thanks, fixed with newest commit on main
