### ISSUE TITLE
Please readd wallpaper feature

### ISSUE THREAD

**Issue by aneverhopefulhelper** [krille-chan/fluffychat#783]
### Feature Description

Add a wallpaper to the background of chats from your own images.

### Rationale

The wallpaper feature that made the cutest matrix client even cuter is gone and I am extremely sad to see it go as now I just have drab chats that are somehow much harder to read, so it is likely an accessibility feature for many too.

I request it be added back so as to make the chats less drab and make them easier to read.

**Comment by laaledesiempre** [comment]
i agree, i dont know the reason but i dont understand why they changed it, in logs they did not added an explanation, i loved fluffychat and i dont want to change to a worst app just for aestethics. i want to belive that they removed that for an excelent reason, and going to add the feature again soon improved. meanwhile, ill be looking for alternarives, even wheni **WANT FLUFFY**
