### ISSUE TITLE
Allow disabling user status segment in chat list

### ISSUE THREAD

**Issue by SteffoSpieler** [krille-chan/fluffychat#784]
### Feature Description

Add a setting to hide / disable this user status segment in the list. The user status feature itself can still remain, of course.

### Rationale

Personally, I am not a big fan of those big user icons that are now at the top of the "Chats" list.
I know it's for the status feature, but it's really big and doesn't really fit in. Also, the text of the actual status doesn't look like it really fits into the new icons. It's short, small, and looks out of place.

But that is just my opinion.

**Comment by LFd3v** [comment]
I second that. For me, the biggest problem is that the user profile picture is too big. Perhaps a smaller pfp with the user status and no username, since the username can be verified after tapping the pfp.

**Comment by viscountexx** [comment]
Thirding. This feature is mostly exposing the status of old contacts I don't talk to and have no plans of talking to anymore.

Also, why was this marked as stale @krille-chan?

**Comment by LFd3v** [comment]
> Also, why was this marked as stale @krille-chan?

I think it was done automatically, since it seems that he is the only one reviewing issues, unfortunately.

**Comment by Fell** [comment]
I use a lot of bridges which don't all support presence. It's confusing to me to have _some_ contacts highlighted especially at the top. It would be nice if I could disable it.

**Comment by SteffoSpieler** [comment]
> Looks like this can be closed with [v1.18.0](https://github.com/krille-chan/fluffychat/releases/tag/v1.18.0). It is also available in the app settings btw.

oh, you're right!
