### ISSUE TITLE
[BUG]: Unable to load timeline

### ISSUE THREAD

**Issue by avtechmjc** [krille-chan/fluffychat#794]
When sharing an image from Tusky (mastodon app) to a group chat in fluffychat:

- Operating system: android
- Version: 1.17.0

### Exception
type 'List<dynamic>' is not a subtype of type 'List<String>' of 'other'

### StackTrace
#0      ListBase.+ (dart:collection/list.dart:345)
#1      MatrixSdkDatabase.getEventList.<anonymous closure> (package:matrix/src/database/matrix_sdk_database.dart:431)
<asynchronous suspension>
#2      Room.getTimeline (package:matrix/src/room.dart:1461)
<asynchronous suspension>
#3      ChatController._getTimeline (package:fluffychat/pages/chat/chat.dart:338)
<asynchronous suspension>
#4      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:624)
<asynchronous suspension>

**Comment by martinhoyer** [comment]
Same here, sharing a screenshot on grapheneOS.
- Operating system: android
- Version: 1.17.0

### Exception
type 'List<dynamic>' is not a subtype of type 'List<String>' of 'other'

### StackTrace
#0      ListBase.+ (dart:collection/list.dart:345)
#1      MatrixSdkDatabase.getEventList.<anonymous closure> (package:matrix/src/database/matrix_sdk_database.dart:431)
<asynchronous suspension>
#2      Room.getTimeline (package:matrix/src/room.dart:1461)
<asynchronous suspension>
#3      ChatController._getTimeline (package:fluffychat/pages/chat/chat.dart:338)
<asynchronous suspension>
#4      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:624)
<asynchronous suspension>

**Comment by TheOneWithTheBraid** [comment]
Fixed in https://github.com/famedly/matrix-dart-sdk/pull/1679.

**Comment by krille-chan** [comment]
I can no longer reproduce it in 1.17.1 so I would assume this is fixed 💪 please reopen and ping me if it happens again
