### ISSUE TITLE
[BUG]: Unable to load timeline

### ISSUE THREAD

**Issue by capsia37** [krille-chan/fluffychat#802]
- Operating system: web
- Version: 1.17.1

### Exception
Concurrent modification during iteration: Instance of 'minified:H<minified:c0>'.

### StackTrace
j@https://fluffychat.im/web/main.dart.js:5608:19
U@https://fluffychat.im/web/main.dart.js:5619:14
p@https://fluffychat.im/web/main.dart.js:70454:24
aRQ/$async$AX<@https://fluffychat.im/web/main.dart.js:226930:15
l/s@https://fluffychat.im/web/main.dart.js:7025:63
$2@https://fluffychat.im/web/main.dart.js:72062:14
$1@https://fluffychat.im/web/main.dart.js:72056:21
a_s@https://fluffychat.im/web/main.dart.js:73392:34
$0@https://fluffychat.im/web/main.dart.js:72533:11
RQ@https://fluffychat.im/web/main.dart.js:7183:40

**Comment by krille-chan** [comment]
Closed as duplication of #799
