### ISSUE TITLE
Image forwarding regression

### ISSUE THREAD

**Issue by replikvlt** [krille-chan/fluffychat#803]
### Bug Description

Forwarding a message with image from one matrix room to another sends image in previous versions (prior to 1.17). 
Now forwarding message with image sends just the image name to other room.

### Steps to Reproduce

1. Send image or select existing in a room;
2. Long tap it to select;
3. Press **Forward**
4. Pick other room
5. Either wait for image to be shared or click send message button with image name.

### Expected Behavior

Image should be shared/forwarded as it did in previous version.

### App Version

1.17.0

### Additional Platform Information

Oppo Reno 5

### Additional Context

(Perhaps other mime types should be tested like videos or other special messages)

**Comment by LFd3v** [comment]
Same problem here on Linux, v1.17.1. Copying and pasting the message also results in something similar (some text with an emoji, but no actual image). It seems that the only way to forward images for now is saving the image then adding it to a new message. =(

**Comment by replikvlt** [comment]
It seems to be fixed in version 1.17.3, with forwarding confirmation dialog. Now images are shared when doing a forwarding from one room to another.     
Closing.
