### ISSUE TITLE
Unable to open fluffychat due to unhandled exception

### ISSUE THREAD

**Issue by JAicewizard** [krille-chan/fluffychat#804]
### Bug Description

Unable to open fluffychat due to an unhandled exception:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected character (at character 1)
```

the basic UI is shown, (titlebar and blue background) but everything supposed to be rendered by flutter is not shown.
No further backtrace is provided

### Steps to Reproduce

1. Open fluffychat

There are probably steps prior to this, but I do not know them.

### Expected Behavior

Fluffychat should display a UI

### App Version

1.16.1

### Additional Platform Information

Arch linux as of 14/1/2024

**Comment by LFd3v** [comment]
Could you please try the [latest version](https://github.com/krille-chan/fluffychat/releases/download/v1.17.1/fluffychat-linux-x64.tar.gz) (download, untar and run the binary). If you still have problems, what DE and CPU/GPU? Just for the record, I have no issues running it on ArchLinux Gnome/Wayland with a hybrid (Optimus = Intel+Nvidia).

**Comment by JAicewizard** [comment]
The issue is that convert/json errors on a file filled with null bytes, erroneously trying to parse an int for no reason whatsoever.
Shared preferences is completely unable to handle corrupt preference files, so I opened an issue to allow resetting them. This would allow fluffychat to reset them on an error.

You can reproduce this by simply corrupting your own preference file.

In the meanwhile I would propose that on an exception when loading the shared preferences fluffychat shows an error, instead of completely nothing. This gives users an indication on what is wrong.

(tested on latest master)

**Comment by JAicewizard** [comment]
https://github.com/flutter/flutter/issues/141575
and see also https://github.com/flutter/flutter/issues/89211
