### ISSUE TITLE
[BUG]: Error Widget

### ISSUE THREAD

**Issue by container1** [krille-chan/fluffychat#807]
- Operating system: android
- Version: 1.17.1

### Exception
Invalid argument(s): HTML had 6 top level elements but 1 expected

### StackTrace
#0      new Element.html (package:html/dom.dart:533)
#1      HtmlMessage._linkifyHtml (package:fluffychat/pages/chat/events/html_message.dart:54)
#2      HtmlMessage._linkifyHtml (package:fluffychat/pages/chat/events/html_message.dart:33)
#3      HtmlMessage._linkifyHtml (package:fluffychat/pages/chat/events/html_message.dart:33)
#4      HtmlMessage._linkifyHtml (package:fluffychat/pages/chat/events/html_message.dart:33)
#5      HtmlMessage.build (package:fluffychat/pages/chat/events/html_message.dart:91)
#6      StatelessElement.build (package:flutter/src/widgets/framework.dart:5541)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)

**Comment by container1** [comment]
Occured at
#synapse:matrix.org
From
{
    "content": {
        "body": "When I test with `ansible-playbook -i inventory/hosts setup.yml --tags=self-check` I get:\n```\nfatal: [my.domain.com]: FAILED! => changed=false \n  msg: 'Failed checking that the well-known file for Client Discovery is configured at `domain.com` (checked endpoint: `https://domain.com/.well-known/matrix/client`). Is port 443 open in your firewall? Full error: {''content'': ''<html>\\r\\n<head><title>404 Not Found</title></head>\\r\\n<body>\\r\\n<center><h1>404 Not Found</h1></center>\\r\\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n'', ''redirected'': False, ''url'': ''https://domain.com/.well-known/matrix/client'', ''status'': 404, ''server'': ''nginx/1.18.0 (Ubuntu)'', ''date'': ''Sun, 14 Jan 2024 15:58:33 GMT'', ''content_type'': ''text/html'', ''content_length'': ''162'', ''connection'': ''close'', ''elapsed'': 0, ''changed'': False, ''failed'': True, ''msg'': ''Status code was 404 and not [200]: HTTP Error 404: Not Found''}'\n```\n",
        "format": "org.matrix.custom.html",
        "formatted_body": "<p>When I test with <code>ansible-playbook -i inventory/hosts setup.yml --tags=self-check</code> I get:</p>\n<pre><code>fatal: [my.domain.com]: FAILED! =&gt; changed=false \n  msg: 'Failed checking that the well-known file for Client Discovery is configured at `domain.com` (checked endpoint: `https://domain.com/.well-known/matrix/client`). Is port 443 open in your firewall? Full error: {''content'': ''&lt;html&gt;\\r\\n&lt;head&gt;&lt;title&gt;404 Not Found&lt;/title&gt;&lt;/head&gt;\\r\\n&lt;body&gt;\\r\\n&lt;center&gt;&lt;h1&gt;404 Not Found&lt;/h1&gt;&lt;/center&gt;\\r\\n&lt;hr&gt;&lt;center&gt;nginx/1.18.0 (Ubuntu)&lt;/center&gt;\\r\\n&lt;/body&gt;\\r\\n&lt;/html&gt;\\r\\n'', ''redirected'': False, ''url'': ''https://domain.com/.well-known/matrix/client'', ''status'': 404, ''server'': ''nginx/1.18.0 (Ubuntu)'', ''date'': ''Sun, 14 Jan 2024 15:58:33 GMT'', ''content_type'': ''text/html'', ''content_length'': ''162'', ''connection'': ''close'', ''elapsed'': 0, ''changed'': False, ''failed'': True, ''msg'': ''Status code was 404 and not [200]: HTTP Error 404: Not Found''}'\n</code></pre>\n",
        "m.mentions": {},
        "msgtype": "m.text"
    },
    "type": "m.room.message",
    "event_id": "$hSaNMll_f1WPyegiP6E-wWHLiZliARE77iiPHGQ1K_k",
    "room_id": "!ehXvUhWNASUkSLvAGP:matrix.org",
    "sender": "@padreug:matrix.org",
    "origin_server_ts": 1705250082532,
    "unsigned": {
        "age": 49586190
    }
}
![Screenshot_20240115-072817](https://github.com/krille-chan/fluffychat/assets/47075899/f0f92d97-0b46-4393-b122-c21a616978b9)

**Comment by LFd3v** [comment]
I think this is a dup of #805 (HTML rendering issues in the new version?).

**Comment by container1** [comment]
Sorry, have not recognized that it's been already stated with #805! 😯
You are right 👍😊
