### ISSUE TITLE
Desktop: Make Escape key work like a back button

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#81]
#### Description
It would be nice for keyboard-heavy use if the desktop version allowed closing foreground views (like dialogs, image previews, the selection menu as described in #358 and the search bar as in #363) and completely different screens (like the settings) by pressing ESC.

#### Additional information:
- Device: Desktop/Laptop
- OS and OS version: Any, probably
- Installed version of FluffyChat: flatpak/stable, updated at the time of writing

/issue fluffy

**Comment by WeebNetsu** [comment]
Can we reopen this issue? I would really like this feature, especially to exit a chat instead of having to interact with the UI
