### ISSUE TITLE
Joining rooms by alias

### ISSUE THREAD

**Issue by meenzen** [krille-chan/fluffychat#815]
### Feature Description

There appears to be no way to join a room by alias using the normal app UI. Even if you're already in the room the search doesn't find it.

Version 1.17.1

### Rationale

Requiring users to join using `matrix.to` links is bad UX. Also that's not a feasible workaround because it's currently broken (see #813). 

### Additional Context

![Screenshot_20240117-073131~2](https://github.com/krille-chan/fluffychat/assets/22305878/2bc5d5c8-8876-43c6-98bf-419ab354d12e)

**Comment by krille-chan** [comment]
fixed in latest commit :)
