### ISSUE TITLE
Don't trim double newlines

### ISSUE THREAD

**Issue by kuba-orlik** [krille-chan/fluffychat#817]
### Feature Description

When sending a message that contains double newlines, don't trim those to single newlines

### Rationale

When writing a long message, it's often useful to separate longer sentences using a double newline, to create a longer paragraph, so to speak. Having the visual separation can be helpful for understanding the structure of the message. Currently double newlines are replaced with single newlines, so this affordance made by the author of the message is lost

**Comment by krille-chan** [comment]
Needs to be done in the  matrix dart sdk. I already wasted enough hours in this...
