### ISSUE TITLE
Can't play OGG audio on iOS

### ISSUE THREAD

**Issue by PgBiel** [krille-chan/fluffychat#818]
### Bug Description

Clicking play on an OGG audio message I received on iOS leads to the error dialog below being shown.

![error dialog](https://github.com/krille-chan/fluffychat/assets/9021226/ab924075-4453-4955-9bfe-283640e496a3)

The full log is:

```
[ERROR] Unable to play audio message - MissingPluginException(No implementation found for method play on channel com.ryanheise.just_audio.methods.bbbbe37e-0bac-448d-8679-3d4387371b7d)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320)
<asynchronous suspension>
#1      [MethodChannelAudioPlayer.play](http://methodchannelaudioplayer.play/) (package:just_audio_platform_interface/method_channel_just_audio.dart:64)
<asynchronous suspension>
#2      AudioPlayer._sendPlayRequest (package:just_audio/just_audio.dart:981)
<asynchronous suspension>
```

However, that error is not shown when playing M4A audio (the format generated by FluffyChat itself, for example). Perhaps other clients generate OGG audio instead.

### Steps to Reproduce

1. Receive or send a .OGG audio message on iOS
2. Click play to listen to it

### Expected Behavior

The audio plays

### App Version

1.17.1

### Additional Platform Information

iPhone 11, iOS 17.2.1

**Comment by krille-chan** [comment]
Needs support by the plugin :-(

**Comment by iamnabink** [comment]
**OGG File Cannot Open iOS:**

This issue stems from the inherent limitations of platform support for various codecs. Apple devices, including iOS, do not natively support OGG files. While this might not be classified as a bug, it does present an opportunity for a feature request. Theoretically, one could manually decode OGG files using software libraries, though this task isn't trivial.

Potential solutions include using an external transcoder like ffmpeg (subject to licensing) to convert the file before playback or leveraging apps like VLC, which can play OGG files on iOS devices. Additionally, for apps where the audio is packaged or produced specifically, developers could consider re-encoding the audio to supported codecs or employing server-side transcoding with tools like ffmpeg.

It might be beneficial to update documentation to include a list of supported file formats for different platforms, aiding users in understanding the compatibility limitations of their devices. For further discussion, you can refer to this thread on the Apple forums: [Supported audio](https://discussions.apple.com/thread/8325833?sortBy=best)

Additionally, in case of **fluffychat**: incorporating a message to inform users that the media format is not supported upon tapping to play would enhance the user experience by providing clear feedback about the issue.

**Comment by krille-chan** [comment]
Should be fixed now :)
