### ISSUE TITLE
Add Ctrl+Backspace shortcut for deleting word

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#82]
#### Description
To write productively in a chat with a hardware keyboard, I'd like to use this familiar shortcut for deleting the word before the cursor position.

#### Additional information:
- Device: Any device with a hardware keyboard (maybe also Android with Hacker's Keyboard)
- OS and OS version: Any
- Installed version of FluffyChat: flatpak/stable / 0.31.1

/issue fluffy

**Comment by PgBiel** [comment]
I believe this issue can be closed; the shortcut seems to work on Linux (Flatpak) and Windows 10. Unless there is still some platform where it doesn't work, perhaps
