### ISSUE TITLE
Ringtone is playing from the earspeaker instead of speaker

### ISSUE THREAD

**Issue by rwbxn** [krille-chan/fluffychat#820]
### Bug Description

Tested on 2 different xiaomi phones, always the same result. Without using a "Calling Account", the ringtone for an incoming phone call is playing through the earspeaker instead of the speaker. The weird thing is, that the ringtone is playing correctly through the loud speaker for 1 second and then it switches to the earpiece.

### Steps to Reproduce

1. Allow all permissions in FluffyChat settings but without "Calling Account", so FluffyChat will use the backup mask
2. Call the Account from Web or second phone
3. Ringtone is coming from speaker for 1second -> stops playing -> and then plays from earspeaker 

### Expected Behavior

The ringtone for incoming calls should be loud and not silent. It should use the main speaker. Can be a problem with flutter-webrtc, see [flutter-webrtc](https://github.com/flutter-webrtc/flutter-webrtc/issues/1032)

### App Version

1.17.1

### Additional Platform Information

Android 13 and 9, MIUI 14.0.6 and MIUI 12.0.1

**Comment by krille-chan** [comment]
Maybe @techno-disaster you can help?
