### ISSUE TITLE
[BUG]: Unable to play audio message

### ISSUE THREAD

**Issue by Haui1112** [krille-chan/fluffychat#821]
- Operating system: ios
- Version: 1.17.1

### Exception
MissingPluginException(No implementation found for method play on channel com.ryanheise.just_audio.methods.1cc3b0d5-8e74-485a-9997-b2b94a6a2f32)

### StackTrace
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320)
<asynchronous suspension>
#1      MethodChannelAudioPlayer.play (package:just_audio_platform_interface/method_channel_just_audio.dart:64)
<asynchronous suspension>
#2      AudioPlayer._sendPlayRequest (package:just_audio/just_audio.dart:981)
<asynchronous suspension>

**Comment by PgBiel** [comment]
Seems to be the same problem as #818
