### ISSUE TITLE
[BUG]: Error Widget

### ISSUE THREAD

**Issue by XSpielinbox** [krille-chan/fluffychat#828]
- Operating system: android
- Version: 1.17.0

### Exception
Null check operator used on a null value

### StackTrace
#0      SelectableRegionState.startGlyphHeight (package:flutter/src/widgets/selectable_region.dart:1211)
#1      SelectableRegionState.contextMenuAnchors (package:flutter/src/widgets/selectable_region.dart:1093)
#2      new AdaptiveTextSelectionToolbar.selectableRegion (package:flutter/src/material/adaptive_text_selection_toolbar.dart:177)
#3      SelectionArea._defaultContextMenuBuilder (package:flutter/src/material/selection_area.dart:96)
#4      SelectableRegionState._onAnyDragEnd.<anonymous closure> (package:flutter/src/widgets/selectable_region.dart:694)
#5      SelectionOverlay.showToolbar.<anonymous closure> (package:flutter/src/widgets/text_selection.dart:1401)
#6      ContextMenuController.show.<anonymous closure> (package:flutter/src/widgets/context_menu_controller.dart:65)
#7      _OverlayEntryWidgetState.build (package:flutter/src/widgets/overlay.dart:356)
#8      StatefulElement.build (package:flutter/src/widgets/framework.dart:5583)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471)
#10     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895)
#13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984)
#14     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457)
#15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255)
#17     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
#18     _invoke (dart:ui/hooks.dart:312)
#19     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
#20     _drawFrame (dart:ui/hooks.dart:283)

**Comment by krille-chan** [comment]
Please add some steps to reproduce this or maybe an example source of an event content. Otherwise I cannot do anything I guess

**Comment by krille-chan** [comment]
Hm can you try again v1.17.2? I have sent this message as raw json into a room and it worked fine for me:

![grafik](https://github.com/krille-chan/fluffychat/assets/24619905/57697718-9076-4117-a349-bd6bb78fff5a)

**Comment by LFd3v** [comment]
It looks like that this issue was fixed as of v1.17.3, so it can be closed?

**Comment by LFd3v** [comment]
Another issue that can be closed as of now, it seems.
