### ISSUE TITLE
Cross certification hangs

### ISSUE THREAD

**Issue by tokudan** [krille-chan/fluffychat#832]
### Bug Description

After #792 I reinstalled Fluffychat on my iOS device to see if that helps with getting it to work, but it now reliably hangs during cross certification when trying to verify against my Element client.
Element shows "Anderes Gerät verifizieren" and just shows a spinning circle after accepting to start the verification.
Fluffychat shows "Anderes Konto wird verifiziert - Warte darauf, dass der Partner die Anfrage annimmt" with a spinning circle that keeps freezing for around 5 seconds every couple of seconds.
After waiting a long time (half an hour or so), Element times out and aborts the verification, Fluffychat just keeps waiting for an hour or more.

### Steps to Reproduce

1. Install Fluffychat
2. Login to synapse server
3. Wait for Fluffychat to request the encryption keys by password or verification of another session
4. Select to request the keys from another session
5. In Element accept the request
6. Fluffychat hangs.

### Expected Behavior

The fluffychat session should get verified.

### App Version

1.17.1

### Additional Platform Information

iPhone SE

**Comment by paddatrapper** [comment]
I experienced the same thing about 2 months ago. It made it impossible to do verification
