### ISSUE TITLE
[BUG]: Error Widget, unable to join via matrix.to link

### ISSUE THREAD

**Issue by StarGazingPie** [krille-chan/fluffychat#838]
- Operating system: android
- Version: 1.17.2

### Exception
Null check operator used on a null value

### StackTrace
#0      PublicRoomBottomSheet.build.<anonymous closure> (package:fluffychat/widgets/public_room_bottom_sheet.dart:151)
#1      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:609)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5583)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)

**Comment by krille-chan** [comment]
Already fixed in newest version 💪

**Comment by LFd3v** [comment]
Sorry, but it does not seem to be fixed, at least not in the latest release (v1.17.2) for Linux, please see https://github.com/krille-chan/fluffychat/issues/813#issuecomment-1912787370.
