### ISSUE TITLE
Option missing to disable vibration when holding down on a message on Android

### ISSUE THREAD

**Issue by jahway603** [krille-chan/fluffychat#847]
### Feature Description

There is no option to disable vibration when holding down on a message on Android. This option could be a toggle on/off or could also be a vibration intensity slider, if the devs believe that would be a better option.

### Rationale

This is an unwanted vibration and there is no feature to control it.

### Additional Context

This is related to iPhone/iOS Issue https://github.com/krille-chan/fluffychat/issues/785, where this vibration function was completely removed.

**Comment by krille-chan** [comment]
We now use `HapticFeedback.selectionClick();` for long press on message which should now work the same as all other long press actions

**Comment by jahway603** [comment]
Alright, so Commit https://github.com/krille-chan/fluffychat/commit/1a655d6f72b26d51d1d6a1916981101a545d93ec fixes this.
