### ISSUE TITLE
[BUG]: Error Widget

### ISSUE THREAD

**Issue by joaogpd** [krille-chan/fluffychat#852]
- Operating system: web
- Version: 1.17.2

### Exception
Bad state: No element

### StackTrace
j@https://fluffychat.im/web/main.dart.js:5609:19
gJ@https://fluffychat.im/web/main.dart.js:70418:9
C@https://fluffychat.im/web/main.dart.js:92454:52
eQ@https://fluffychat.im/web/main.dart.js:142220:28
zx@https://fluffychat.im/web/main.dart.js:142194:9
zx@https://fluffychat.im/web/main.dart.js:142230:11
aan@https://fluffychat.im/web/main.dart.js:142146:10
aMK@https://fluffychat.im/web/main.dart.js:142147:19
afe@https://fluffychat.im/web/main.dart.js:142192:12
afe@https://fluffychat.im/web/main.dart.js:142227:3

This seems to happen when I try to drag an image that was sent to me while having right clicked it just before and having the dropdown menu show and then close (or this was just when it happened to me, but I haven't been able to do this without going through this step, though not due to lack of trying). If I drag the image, it shows an Upload symbol and if I let go of the selected image, I am greeted with this error. I have been able to reproduce it, though not quite consistently. Sometimes it happens in my first try after having right clicked the image and other times I need to try it multiple times until I can reproduce it. 

https://github.com/krille-chan/fluffychat/assets/101755823/184cf4d1-a83b-48a4-90ad-ba9b324a4061

EDIT: After further testing, this does not seem to be exclusive to images, happening with any message overall, following the same order of operations.

**Comment by krille-chan** [comment]
Thank you :) fixed with latest commit and also added a check for the file size before loading the bytes
