### ISSUE TITLE
Bug: unable to leave chat with user from defederated instance

### ISSUE THREAD

**Issue by lolbinarycat** [krille-chan/fluffychat#873]
### Bug Description

i can't send messages and it won't let me leave

### Steps to Reproduce

1. send chat invite to user on blocked instance, FluffyChat will then create a broken room
2. go into the room and select "leave chat"
3. the room will now be at the top of your contacts instead of disappearing 

### Expected Behavior

the room should be removed from the list no matter the response from the server

### App Version

1.16.0

### Additional Platform Information

F-Droid, Pixel 7a

**Comment by LFd3v** [comment]
1. Can you please try this using the latest version (v1.17.3)?

2. If the issue still happens, it also happens with other Android clients like Schildichat or Element? If yes, then it is a Matrix (protocol problem).

**Comment by lolbinarycat** [comment]
seems to be fixed on the newest release, though i'm not sure if that was due to the database migration or the underlying issue being fixed.
