### ISSUE TITLE
Help is needed

### ISSUE THREAD

**Issue by talshanisherman** [krille-chan/fluffychat#882]
### Bug Description

Hi,
I am new to fluffychat and matrix
I have two issues which maybe a bug, or maybe I don't understand well enough of how to use the platform
I create an element one matrix account on the web and there I receive chats and messages fine
I wish to see those messages in the fluffychat account, I have imported spaces from my matrix account, but nothing happens and no calls or chats are coming through, 
Please help me to modify it correctly
![image](https://github.com/krille-chan/fluffychat/assets/125541306/fe9df2fc-0810-470b-a3c1-e5fa0179a123)
A second issue
It says there is a windows app, but I can not find how to download it
![image](https://github.com/krille-chan/fluffychat/assets/125541306/78e9b225-7791-4baf-a8eb-469c3d109007)
Print screens attached
Thanks
Tal

### Steps to Reproduce

1. go to fluffychat
2. trying to import the chats fails

### Expected Behavior

I thought that after importing the spaces, chats and messages would appear

### App Version

1.17.3

### Additional Platform Information

Web

**Comment by LFd3v** [comment]
Hi, there. I will try to help you out:

1. GitHub is meant to be used to track problems with the app (bugs, new features, etc), a better place to ask for help using it is better suited for the FluffyChat room on Matrix: https://matrix.to/#/#fluffychat:matrix.org

2. Matrix a messenger protocol that is meant to be decentralized, anyone can host a server too, it is also open source. Anyone can login to an account, from matrix.org for instance, to any client, like Element on web, Element for Android, Desktop or iOS, and FluffyChat. So you can use the same account on multiple clients (just make sure you verify every new client properly using an older client so you can read encrypted messages in the new one (if you want it to be this way, of course)

3. What do you mean by "import chats" exactly? Normally this is not needed: once you login using the same account and verify it on a new device or client (see above), all your rooms and messages will be available there as well

4. The Windows version was not released officially, you can either use the web app as PWA (progressive web app). More info and further changes can be found in #162.

PS: If this answers your doubts or you need further help, please join the Matrix room and close this issue. Thank you.

**Comment by talshanisherman** [comment]
Thanks
Helped a lot
Closing the bug

**Comment by LFd3v** [comment]
@krille-chan OP did not close this issue so far, maybe you want to do it.
