### ISSUE TITLE
[BUG]: Error Widget - adding a space.

### ISSUE THREAD

**Issue by p4p4j0hn** [krille-chan/fluffychat#885]
Trying to add #podverse-space:matrix.org fails.

- Operating system: android
- Version: 1.17.2

### Exception
Null check operator used on a null value

### StackTrace
#0      PublicRoomBottomSheet.build.<anonymous closure> (package:fluffychat/widgets/public_room_bottom_sheet.dart:151)
#1      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:609)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5583)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)

**Comment by krille-chan** [comment]
This crash is already fixed in v1.17.3 please update your app

**Comment by p4p4j0hn** [comment]
I installed with F-droid. I will just have to wait until it is released. Thanks.
