### ISSUE TITLE
Add search for messages in room

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#9]
#### Description
It would be nice to search for messages (or also other events) in a room.

The Matrix protocol even has an API for that: https://matrix.org/docs/spec/client_server/r0.4.0#id137
And it seems like the famedlysdk already implements it.

I suggest to do it, like the Element Web-UI already does it:

- Show matching messages as search result
- Show context around the message when the user clicks on a result

**Comment by CleoMenezesJr** [comment]
Hope to see this soon. o/

**Comment by throwException** [comment]
I would really like to see this feature.
