### ISSUE TITLE
error unable to buil  the SQlite database. The app tries to ...

### ISSUE THREAD

**Issue by alexlehm** [krille-chan/fluffychat#901]
### Bug Description

After running fluffychat for a while on android, I get the error message that the SQlite database cannot be opened

### Steps to Reproduce

I am not sure how to reproduce that directly
I installed Fluffychat about 3 says ago, i used it seldomly and the error appeared (and the app is logged out)

### Expected Behavior

I would expect the app not to corrupt the database

### App Version

1.17.3 android

### Additional Platform Information

Android Samsung S7

### Additional Context

After the app is in this state a new login does not work at all

**Comment by krille-chan** [comment]
Hey, can you try to clear the cache of the app?

**Comment by alexlehm** [comment]
i fixed it by clearing all files and logging in again, i didn't get the idea to clear the cache only
i will see if it happens again and retry
