### ISSUE TITLE
Notifications automatically open on android

### ISSUE THREAD

**Issue by NepNep21** [krille-chan/fluffychat#902]
### Bug Description

Most commonly after unlocking the phone, but also occasionally in the app itself, if you have more than a few fluffychat notifications they will automatically open. I'm not sure about the flutter side of it, but it seems like it might be calling [this](https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html#setFullScreenIntent(android.app.PendingIntent,%20boolean)) internally?

### Steps to Reproduce

1. Lock your phone.
2. Let a few notifications pile up.
3. Unlock your phone
4. Potentially try again a few times.

### Expected Behavior

Notifications in a chat client should not open without user interaction.

### App Version

a6b5acb451d2f3352d4e89eb8fdd9204604c9d52, it does not occur in the latest release.

### Additional Platform Information

Poco F3, DivestOS (android ROM).

**Comment by NepNep21** [comment]
Just did a bit of testing, the following patch prevents that from happening:
```patch
diff --git a/lib/utils/push_helper.dart b/lib/utils/push_helper.dart
index 520db7de..d8ab65ae 100644
--- a/lib/utils/push_helper.dart
+++ b/lib/utils/push_helper.dart
@@ -60,10 +60,10 @@ Future<void> pushHelper(
           l10n.incomingMessages,
           number: notification.counts?.unread,
           ticker: l10n.unreadChats(notification.counts?.unread ?? 1),
-          importance: Importance.max,
+          importance: Importance.high,
           priority: Priority.max,
           shortcutId: notification.roomId,
-          fullScreenIntent: true, // To show notification popup
+          fullScreenIntent: false, // To show notification popup
         ),
       ),
     );
@@ -272,10 +272,10 @@ Future<void> _tryPushHelper(
           messages: [newMessage],
         ),
     ticker: l10n.unreadChats(notification.counts?.unread ?? 1),
-    importance: Importance.max,
+    importance: Importance.high,
     priority: Priority.max,
     groupKey: notificationGroupId,
-    fullScreenIntent: true, // To show notification popup
+    fullScreenIntent: false, // To show notification popup
   );
   const iOSPlatformChannelSpecifics = DarwinNotificationDetails();
   final platformChannelSpecifics = NotificationDetails(
```
However, that brings up 2 other issues:
1. Those lines have *not* been changed since the latest release, so there must be something else that causes it when combined with them, I am not sure what.
2. I do not know if the patch breaks some other part of notifications, though FWIW it seems fine to me.

Any ideas?

**Comment by krille-chan** [comment]
thanks @NepNep21 I'd say those lines should be safe to be changed as you said. The importance.high value is used in Famedly since the beginning and seems to work the same. The fullScreenIntent isn't working ootb anyway so it is also saved to be removed.

Probably the issue occured because of the changes to Conversation style messages.

I have applied your changes in the latest commit on main. Let's see if this fixes it...

**Comment by NepNep21** [comment]
Thank you ^^
