### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [krille-chan/fluffychat#908]
...as [`core-google-shortcuts`](https://github.com/krille-chan/flutter_shortcuts/blob/main/android/build.gradle#L34) is not FOSS since it depends on [proprietary Google libs](https://mvnrepository.com/artifact/androidx.core/core-google-shortcuts/1.1.0) 

ref: https://github.com/krille-chan/fluffychat/commit/dee9323d4749b7b5778ada8ab1fcbf07f8f51936#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25R50

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/373888c541b54a5b77f1abf6f7c0133bf52cab15

**Comment by linsui** [comment]
I thought we can remove it directly with a sed?

**Comment by licaon-kter** [comment]
Maybe we can, maybe we can't :) not sure what happens when we remove `core-google-shortcuts`

**Comment by licaon-kter** [comment]
great https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14601/diffs
