### ISSUE TITLE
FluffyChat 1.18.0 from Flatpak does not honor notification settings

### ISSUE THREAD

**Issue by michel-slm** [krille-chan/fluffychat#913]
### Bug Description

After turning off notifications in Settings -> Notifications -> Notifications enabled for this account, I am still getting notifications (Fedora 39, GNOME 45). Restarted FluffyChat to be sure and this is still happening

### Steps to Reproduce

1. `flatpak install im.fluffychat.Fluffychat`
2. Start FluffyChat
3. Log in
4. Join a busy room like #meeting:fedoraproject.org or #meeting-1:fedoraproject.org
5. Disable notifications

### Expected Behavior

Notifications should be disabled

### App Version

1.18.0

### Additional Platform Information

Thinkpad T490s, Fedora Linux Workstation 39, FluffyChat installed via flatpak from flathub

**Comment by krille-chan** [comment]
I cannot reproduce this. Sounds more like a server-error to me and not a client problem
