### ISSUE TITLE
Fallback E2EE refers to Pantalaimon confusing everyone

### ISSUE THREAD

**Issue by Mikaela** [krille-chan/fluffychat#936]
### Bug Description

When something goes wrong with encryption, FluffyChat errorneously gives the legacy warning about needing Pantalaimon which hasn't been the case in ages.

### Steps to Reproduce

unknown

### Expected Behavior

FluffyChat will instead say that it doesn't know what is wrong if it really doesn't know.

### App Version

unknown

### Additional Platform Information

any

### Additional Context

I only know of this having been confused when localizing the string previously.

**Comment by krille-chan** [comment]
Fixed :)

**Comment by Mikaela** [comment]
Ref: https://github.com/krille-chan/fluffychat/commit/a31dce0a21d9a0dceaee306cda52fe187990ecce

Yet another thing I need to fix in the translation now (at least when it syncs if not already) 😅
