### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by xtr3mz** [krille-chan/fluffychat#950]
### Feature Description

1. sign up page
2. include :ntfy / xiaomi push
3. other functions , please try wechat.apk
4. smaller emoji 

### Rationale

user friendly, easier to use

**Comment by Mikaela** [comment]
1. Blocked by https://areweoidcyet.com/
2. Already supported. https://github.com/krille-chan/fluffychat/wiki/Push-Notifications-without-Google-Services
3. I don't think anyone will
4. I think it comes from your system font size.
