### ISSUE TITLE
Multiple equal reactions from user are displayed multiple times

### ISSUE THREAD

**Issue by Kladki** [krille-chan/fluffychat#952]
### Bug Description

When multiple `m.reaction` events are sent from a user with the same `key` and `rel_type` from the same user, it causes their reactions to add up rather than just being displayed once. 
![Screenshot_2024-03-24-16-59-11-344-edit_chat fluffy fluffychat](https://github.com/krille-chan/fluffychat/assets/158313939/80c6090b-f7d8-4be1-ba8b-e3a2ed3118fc)
![Screenshot_2024-03-24-16-59-47-865-edit_chat fluffy fluffychat](https://github.com/krille-chan/fluffychat/assets/158313939/469bf654-eac8-4122-b6df-69d8132663ed)

### Steps to Reproduce

1. Send a message
2. Get the event id
3. Use element devtools to send this event multiple times of type `m.reaction`:
```json
"m.relates_to": {
  "event_id": "${event_id}",
  "key": "👍",
  "rel_type": "m.annotation"
}
```
4. See issue

### Expected Behavior

Only one reaction of a certain emoji should be displayed for a single user.
> Multiple identical annotations (i.e., with the same event type and annotation key) from the same user (i.e., events with the same sender) should be treated as a single annotation.

https://spec.matrix.org/v1.10/client-server-api/#annotations-client-behaviour

### App Version

1.18.0

### Additional Platform Information

Redmi Note 9 Pro, Android 12

### Additional Context

Multiple reactions in the real world can be caused  by buggy clients, multiple clients reacting at the same time, lag, etc.

**Comment by krille-chan** [comment]
Thanks for the bug report. I will move the issue to the sdk repo

**Comment by krille-chan** [comment]
Closed in favor of https://github.com/famedly/matrix-dart-sdk/issues/1752
