### ISSUE TITLE
Cannot find account registration

### ISSUE THREAD

**Issue by fgcle** [krille-chan/fluffychat#955]
### Bug Description

Tested on Android (without GSF) and on Linux using Snap. I cannot find the place where I can *register* an account. Some other bugs here mention a so-called 'registration view' but please somebody tell me how to open it. When I open the program it greets me with oodles of "LOGIN with [blabla]" buttons, and nothing suggests how to register instead of log in.

I wanted to ask this question in #fluffychat:matrix.org but all clients I'm using tell me that 'auth events are missing' so I could not join there. Therefore I'm asking here even if I think the mentioned chat would be the best place for my question.

### Steps to Reproduce

How to reproduce:
* install FluffyChat
* run it for the first time
* see the greeting screen with only LOGIN buttons

### Expected Behavior

Expected behaviour
* see at least any little sign that hints how to REGISTER.

### App Version

Snap rc1.18.0-2, or Android 1.18.0

### Additional Platform Information

not important

**Comment by krille-chan** [comment]
There is no in-app registration anymore in FluffyChat. You can register an account by using SSO or on external sites and then return to FluffyChat. The in-app registration for Matrix will soon be deprecated anyway in favor of OIDC and previous attempts to implement it, were too buggy so it was removed

**Comment by fgcle** [comment]
I cannot believe that a (protocol-wise) well-specified workflow like in-app registration be on the course of being abandoned. All clients but one implement it. So I can only advise my users to use any other client for that. (and, if it is really as you described -- advise them to hurry until registration will be phased out entirely).

**Comment by JaredTRand** [comment]
yeah wait, why is this?? This is the one reason I'm not telling my users to use Fluffychat. It's already hard enough to get people to download one more app, but to tell them they have to register on another site/app and _then_ go to use fluffychat? Seems silly

**Comment by shocklateboy92** [comment]
Okay, to confirm: if we enable SSO with matrix-authentication-service on our server, users will be about to register accounts on our server using Fluffychat?

**Comment by Buer-Nahida** [comment]
> Okay, to confirm: if we enable SSO with matrix-authentication-service on our server, users will be about to register accounts on our server using Fluffychat?

Yes, if login website that your SSO provider provided has a sign up option (I tested Auth0).
