### ISSUE TITLE
Can't login google

### ISSUE THREAD

**Issue by ozky84** [krille-chan/fluffychat#978]
### Bug Description

login problems, Here is log, gui only say something goes wrong...this is FLatpak Linux x86_64...

flutter: [Matrix] Unable to clear database - HiveError: Box has already been closed.
#0      BoxBaseImpl.checkOpen (package:hive/src/box/box_base_impl.dart:76)
#1      BoxBaseImpl.keys (package:hive/src/box/box_base_impl.dart:56)
#2      CollectionBox.clear (package:hive/src/box_collection/box_collection.dart:223)
<asynchronous suspension>
#3      HiveCollectionsDatabase.clear.<anonymous closure> (package:matrix/src/database/hive_collections_database.dart:247)
<asynchronous suspension>
#4      BoxCollection.transaction.<anonymous closure> (package:hive/src/box_collection/box_collection.dart:79)
<asynchronous suspension>
#5      BoxCollection.transaction (package:hive/src/box_collection/box_collection.dart:76)
<asynchronous suspension>
#6      Client.clear (package:matrix/src/client.dart:1774)
<asynchronous suspension>
#7      Client.init (package:matrix/src/client.dart:1757)
<asynchronous suspension>
#8      Client.login (package:matrix/src/client.dart:627)
<asynchronous suspension>
#9      HomeserverPickerController.ssoLoginAction (package:fluffychat/pages/homeserver_picker/homeserver_picker.dart:145)
<asynchronous suspension>

Here is log...
flutter: [Matrix] Something went wrong:  - HiveError: Box has already been closed.

** (fluffychat:2): WARNING **: 18:59:07.682: libsecret_error: 
\xdd\xe4]\x84U
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Missing extension byte (at offset 2)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1741)
#1      Utf8Decoder.convert (dart:convert/utf.dart:349)
#2      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:502)
#3      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:477)
#4      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:647)
#5      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
<asynchronous suspension>
#6      InitWithRestoreExtension.deleteSessionBackup (package:fluffychat/utils/init_with_restore.dart:59)
<asynchronous suspension>

flutter: [Matrix] Set background mode in VOIP plugin - false
flutter: [Matrix] Set background mode in VOIP plugin - false
`

### Steps to Reproduce

Use terminal to start it 

### Expected Behavior

don't know

### App Version

v1.19.0

### Additional Platform Information

Linux

**Comment by ozky84** [comment]
[fky.txt](https://github.com/krille-chan/fluffychat/files/14855207/fky.txt)

**Comment by krille-chan** [comment]
Duplication of https://github.com/krille-chan/fluffychat/issues/972

**Comment by ozky84** [comment]
Okay thanks, i not notice all it's duplicate...
