### ISSUE TITLE
New style of themes ruin legibility

### ISSUE THREAD

**Issue by butter-radish** [krille-chan/fluffychat#981]
### Bug Description

I opened my install of the app to find that, while using the light theme version of the colour themes, my message bubbles now have a dark-coloured background with white text. This is a regression.

I use a light theme, not for the background to prominently be white, but to read dark text over a light background. Inverting the colours this way, making me read white text, ruins legibility.

### Steps to Reproduce

1. Open the app.
2. Open a chat.

### Expected Behavior

All message bubbles are set with dark-coloured text over a light-coloured background, in the light colour themes. And the inverse in the dark colour themes.

### App Version

1.19.0

### Additional Platform Information

iOS

**Comment by krille-chan** [comment]
Can you elaborate why it ruins the legibility when having white text on dark background in light mode?
