### ISSUE TITLE
Unable to build the SQlite database

### ISSUE THREAD

**Issue by Lexden12** [krille-chan/fluffychat#985]
### Bug Description

Hello, I performed a fresh install of FluffyChat on Arch using the flatpak. Upon starting the app, I immediately get a notification stating:
Unable to build the SQlite database. The app tries to use the legacy database for now. Please report this error to the developers at https://github.com/krille-chan/fluffychat/issues/new. The error message is: Null check operator used on a null value.

This does not allow me to log in.

### Steps to Reproduce

1. Install FluffyChat using the flatpak.
2. Observe a notification stating that it was unable to build the SQlite database.
3. Enter homeserver in the Homeserver textbox
4. Click "Sign in with password"
5. Enter credentials and hit enter
6. Fluffychat suddenly returns to the page with the "Sign in with password" button
7. Click the "Sign in with password" button again
8. Observe that the top now says "Log in to null" rather than the homeserver.

### Expected Behavior

I expect it to log in successfully and not kick me out to the login page.

### App Version

1.19.0

### Additional Platform Information

Linux Flatpak from Flathub: https://flathub.org/apps/im.fluffychat.Fluffychat

### Additional Context

Fluffychat otherwise works perfectly well in the browser and on Android. Thank you for this great Matrix front-end!

**Comment by krille-chan** [comment]
Duplication of https://github.com/krille-chan/fluffychat/issues/972
